package cn.emoney.acg.data.protocol.motif;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuyClubList_Reply.proto

public final class BuyClubListReply {
  private BuyClubListReply() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuyClubList_ReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 class_type = 4;
    /**
     * <code>required int32 class_type = 4;</code>
     *
     * <pre>
     * 0:正常排序列表  1:"我的组合"
     * </pre>
     */
    boolean hasClassType();
    /**
     * <code>required int32 class_type = 4;</code>
     *
     * <pre>
     * 0:正常排序列表  1:"我的组合"
     * </pre>
     */
    int getClassType();

    // repeated int32 rep_fields = 5 [packed = true];
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    java.util.List<java.lang.Integer> getRepFieldsList();
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    int getRepFieldsCount();
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    int getRepFields(int index);

    // repeated .BuyClubList_Reply.GroupData group_list = 6;
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData> 
        getGroupListList();
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    BuyClubListReply.BuyClubList_Reply.GroupData getGroupList(int index);
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    int getGroupListCount();
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    java.util.List<? extends BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder> 
        getGroupListOrBuilderList();
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder getGroupListOrBuilder(
        int index);

    // required uint32 rep_begin = 7;
    /**
     * <code>required uint32 rep_begin = 7;</code>
     *
     * <pre>
     *起始位置
     * </pre>
     */
    boolean hasRepBegin();
    /**
     * <code>required uint32 rep_begin = 7;</code>
     *
     * <pre>
     *起始位置
     * </pre>
     */
    int getRepBegin();

    // required uint32 total_size = 8;
    /**
     * <code>required uint32 total_size = 8;</code>
     *
     * <pre>
     *总大小
     * </pre>
     */
    boolean hasTotalSize();
    /**
     * <code>required uint32 total_size = 8;</code>
     *
     * <pre>
     *总大小
     * </pre>
     */
    int getTotalSize();

    // required int32 sort_field = 9;
    /**
     * <code>required int32 sort_field = 9;</code>
     *
     * <pre>
     *请求的排序字段
     * </pre>
     */
    boolean hasSortField();
    /**
     * <code>required int32 sort_field = 9;</code>
     *
     * <pre>
     *请求的排序字段
     * </pre>
     */
    int getSortField();

    // required bool sort_order = 10;
    /**
     * <code>required bool sort_order = 10;</code>
     *
     * <pre>
     *请求的升降序
     * </pre>
     */
    boolean hasSortOrder();
    /**
     * <code>required bool sort_order = 10;</code>
     *
     * <pre>
     *请求的升降序
     * </pre>
     */
    boolean getSortOrder();

    // required string icon_url_pre = 11;
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    boolean hasIconUrlPre();
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    java.lang.String getIconUrlPre();
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    com.google.protobuf.ByteString
        getIconUrlPreBytes();

    // optional uint32 req_flag = 12;
    /**
     * <code>optional uint32 req_flag = 12;</code>
     *
     * <pre>
     *请求标识符
     * </pre>
     */
    boolean hasReqFlag();
    /**
     * <code>optional uint32 req_flag = 12;</code>
     *
     * <pre>
     *请求标识符
     * </pre>
     */
    int getReqFlag();
  }
  /**
   * Protobuf type {@code BuyClubList_Reply}
   */
  public static final class BuyClubList_Reply extends
      com.google.protobuf.GeneratedMessage
      implements BuyClubList_ReplyOrBuilder {
    // Use BuyClubList_Reply.newBuilder() to construct.
    private BuyClubList_Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuyClubList_Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuyClubList_Reply defaultInstance;
    public static BuyClubList_Reply getDefaultInstance() {
      return defaultInstance;
    }

    public BuyClubList_Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuyClubList_Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000001;
              classType_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                repFields_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              repFields_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                repFields_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                repFields_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                groupList_ = new java.util.ArrayList<BuyClubListReply.BuyClubList_Reply.GroupData>();
                mutable_bitField0_ |= 0x00000004;
              }
              groupList_.add(input.readMessage(BuyClubListReply.BuyClubList_Reply.GroupData.PARSER, extensionRegistry));
              break;
            }
            case 56: {
              bitField0_ |= 0x00000002;
              repBegin_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000004;
              totalSize_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000008;
              sortField_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000010;
              sortOrder_ = input.readBool();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000020;
              iconUrlPre_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000040;
              reqFlag_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          repFields_ = java.util.Collections.unmodifiableList(repFields_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          groupList_ = java.util.Collections.unmodifiableList(groupList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BuyClubListReply.internal_static_BuyClubList_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BuyClubListReply.internal_static_BuyClubList_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BuyClubListReply.BuyClubList_Reply.class, BuyClubListReply.BuyClubList_Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<BuyClubList_Reply> PARSER =
        new com.google.protobuf.AbstractParser<BuyClubList_Reply>() {
      public BuyClubList_Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuyClubList_Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuyClubList_Reply> getParserForType() {
      return PARSER;
    }

    public interface GroupDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required uint32 group_id = 1;
      /**
       * <code>required uint32 group_id = 1;</code>
       *
       * <pre>
       *组合代码
       * </pre>
       */
      boolean hasGroupId();
      /**
       * <code>required uint32 group_id = 1;</code>
       *
       * <pre>
       *组合代码
       * </pre>
       */
      int getGroupId();

      // required int32 state = 2;
      /**
       * <code>required int32 state = 2;</code>
       *
       * <pre>
       *1:推荐  2:new  3:hot  0:无  
       * </pre>
       */
      boolean hasState();
      /**
       * <code>required int32 state = 2;</code>
       *
       * <pre>
       *1:推荐  2:new  3:hot  0:无  
       * </pre>
       */
      int getState();

      // repeated string rep_field_value = 3;
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      java.util.List<java.lang.String>
      getRepFieldValueList();
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      int getRepFieldValueCount();
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      java.lang.String getRepFieldValue(int index);
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      com.google.protobuf.ByteString
          getRepFieldValueBytes(int index);
    }
    /**
     * Protobuf type {@code BuyClubList_Reply.GroupData}
     */
    public static final class GroupData extends
        com.google.protobuf.GeneratedMessage
        implements GroupDataOrBuilder {
      // Use GroupData.newBuilder() to construct.
      private GroupData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private GroupData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final GroupData defaultInstance;
      public static GroupData getDefaultInstance() {
        return defaultInstance;
      }

      public GroupData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private GroupData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                groupId_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                state_ = input.readInt32();
                break;
              }
              case 26: {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  repFieldValue_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                repFieldValue_.add(input.readBytes());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            repFieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(repFieldValue_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BuyClubListReply.internal_static_BuyClubList_Reply_GroupData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BuyClubListReply.internal_static_BuyClubList_Reply_GroupData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BuyClubListReply.BuyClubList_Reply.GroupData.class, BuyClubListReply.BuyClubList_Reply.GroupData.Builder.class);
      }

      public static com.google.protobuf.Parser<GroupData> PARSER =
          new com.google.protobuf.AbstractParser<GroupData>() {
        public GroupData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GroupData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<GroupData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required uint32 group_id = 1;
      public static final int GROUP_ID_FIELD_NUMBER = 1;
      private int groupId_;
      /**
       * <code>required uint32 group_id = 1;</code>
       *
       * <pre>
       *组合代码
       * </pre>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 group_id = 1;</code>
       *
       * <pre>
       *组合代码
       * </pre>
       */
      public int getGroupId() {
        return groupId_;
      }

      // required int32 state = 2;
      public static final int STATE_FIELD_NUMBER = 2;
      private int state_;
      /**
       * <code>required int32 state = 2;</code>
       *
       * <pre>
       *1:推荐  2:new  3:hot  0:无  
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 state = 2;</code>
       *
       * <pre>
       *1:推荐  2:new  3:hot  0:无  
       * </pre>
       */
      public int getState() {
        return state_;
      }

      // repeated string rep_field_value = 3;
      public static final int REP_FIELD_VALUE_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList repFieldValue_;
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      public java.util.List<java.lang.String>
          getRepFieldValueList() {
        return repFieldValue_;
      }
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      public int getRepFieldValueCount() {
        return repFieldValue_.size();
      }
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      public java.lang.String getRepFieldValue(int index) {
        return repFieldValue_.get(index);
      }
      /**
       * <code>repeated string rep_field_value = 3;</code>
       *
       * <pre>
       *字段具体行情值，按回复字段顺序来
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRepFieldValueBytes(int index) {
        return repFieldValue_.getByteString(index);
      }

      private void initFields() {
        groupId_ = 0;
        state_ = 0;
        repFieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasGroupId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasState()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, groupId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, state_);
        }
        for (int i = 0; i < repFieldValue_.size(); i++) {
          output.writeBytes(3, repFieldValue_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, groupId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, state_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < repFieldValue_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(repFieldValue_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getRepFieldValueList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static BuyClubListReply.BuyClubList_Reply.GroupData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(BuyClubListReply.BuyClubList_Reply.GroupData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BuyClubList_Reply.GroupData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return BuyClubListReply.internal_static_BuyClubList_Reply_GroupData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return BuyClubListReply.internal_static_BuyClubList_Reply_GroupData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  BuyClubListReply.BuyClubList_Reply.GroupData.class, BuyClubListReply.BuyClubList_Reply.GroupData.Builder.class);
        }

        // Construct using BuyClubListReply.BuyClubList_Reply.GroupData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          groupId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          state_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          repFieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return BuyClubListReply.internal_static_BuyClubList_Reply_GroupData_descriptor;
        }

        public BuyClubListReply.BuyClubList_Reply.GroupData getDefaultInstanceForType() {
          return BuyClubListReply.BuyClubList_Reply.GroupData.getDefaultInstance();
        }

        public BuyClubListReply.BuyClubList_Reply.GroupData build() {
          BuyClubListReply.BuyClubList_Reply.GroupData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public BuyClubListReply.BuyClubList_Reply.GroupData buildPartial() {
          BuyClubListReply.BuyClubList_Reply.GroupData result = new BuyClubListReply.BuyClubList_Reply.GroupData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.groupId_ = groupId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.state_ = state_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            repFieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
                repFieldValue_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.repFieldValue_ = repFieldValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof BuyClubListReply.BuyClubList_Reply.GroupData) {
            return mergeFrom((BuyClubListReply.BuyClubList_Reply.GroupData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(BuyClubListReply.BuyClubList_Reply.GroupData other) {
          if (other == BuyClubListReply.BuyClubList_Reply.GroupData.getDefaultInstance()) return this;
          if (other.hasGroupId()) {
            setGroupId(other.getGroupId());
          }
          if (other.hasState()) {
            setState(other.getState());
          }
          if (!other.repFieldValue_.isEmpty()) {
            if (repFieldValue_.isEmpty()) {
              repFieldValue_ = other.repFieldValue_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRepFieldValueIsMutable();
              repFieldValue_.addAll(other.repFieldValue_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasGroupId()) {
            
            return false;
          }
          if (!hasState()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          BuyClubListReply.BuyClubList_Reply.GroupData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (BuyClubListReply.BuyClubList_Reply.GroupData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required uint32 group_id = 1;
        private int groupId_ ;
        /**
         * <code>required uint32 group_id = 1;</code>
         *
         * <pre>
         *组合代码
         * </pre>
         */
        public boolean hasGroupId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 group_id = 1;</code>
         *
         * <pre>
         *组合代码
         * </pre>
         */
        public int getGroupId() {
          return groupId_;
        }
        /**
         * <code>required uint32 group_id = 1;</code>
         *
         * <pre>
         *组合代码
         * </pre>
         */
        public Builder setGroupId(int value) {
          bitField0_ |= 0x00000001;
          groupId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 group_id = 1;</code>
         *
         * <pre>
         *组合代码
         * </pre>
         */
        public Builder clearGroupId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          groupId_ = 0;
          onChanged();
          return this;
        }

        // required int32 state = 2;
        private int state_ ;
        /**
         * <code>required int32 state = 2;</code>
         *
         * <pre>
         *1:推荐  2:new  3:hot  0:无  
         * </pre>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 state = 2;</code>
         *
         * <pre>
         *1:推荐  2:new  3:hot  0:无  
         * </pre>
         */
        public int getState() {
          return state_;
        }
        /**
         * <code>required int32 state = 2;</code>
         *
         * <pre>
         *1:推荐  2:new  3:hot  0:无  
         * </pre>
         */
        public Builder setState(int value) {
          bitField0_ |= 0x00000002;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 state = 2;</code>
         *
         * <pre>
         *1:推荐  2:new  3:hot  0:无  
         * </pre>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000002);
          state_ = 0;
          onChanged();
          return this;
        }

        // repeated string rep_field_value = 3;
        private com.google.protobuf.LazyStringList repFieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureRepFieldValueIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            repFieldValue_ = new com.google.protobuf.LazyStringArrayList(repFieldValue_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public java.util.List<java.lang.String>
            getRepFieldValueList() {
          return java.util.Collections.unmodifiableList(repFieldValue_);
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public int getRepFieldValueCount() {
          return repFieldValue_.size();
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public java.lang.String getRepFieldValue(int index) {
          return repFieldValue_.get(index);
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public com.google.protobuf.ByteString
            getRepFieldValueBytes(int index) {
          return repFieldValue_.getByteString(index);
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public Builder setRepFieldValue(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureRepFieldValueIsMutable();
          repFieldValue_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public Builder addRepFieldValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureRepFieldValueIsMutable();
          repFieldValue_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public Builder addAllRepFieldValue(
            java.lang.Iterable<java.lang.String> values) {
          ensureRepFieldValueIsMutable();
          super.addAll(values, repFieldValue_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public Builder clearRepFieldValue() {
          repFieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string rep_field_value = 3;</code>
         *
         * <pre>
         *字段具体行情值，按回复字段顺序来
         * </pre>
         */
        public Builder addRepFieldValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureRepFieldValueIsMutable();
          repFieldValue_.add(value);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:BuyClubList_Reply.GroupData)
      }

      static {
        defaultInstance = new GroupData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:BuyClubList_Reply.GroupData)
    }

    private int bitField0_;
    // required int32 class_type = 4;
    public static final int CLASS_TYPE_FIELD_NUMBER = 4;
    private int classType_;
    /**
     * <code>required int32 class_type = 4;</code>
     *
     * <pre>
     * 0:正常排序列表  1:"我的组合"
     * </pre>
     */
    public boolean hasClassType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 class_type = 4;</code>
     *
     * <pre>
     * 0:正常排序列表  1:"我的组合"
     * </pre>
     */
    public int getClassType() {
      return classType_;
    }

    // repeated int32 rep_fields = 5 [packed = true];
    public static final int REP_FIELDS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> repFields_;
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getRepFieldsList() {
      return repFields_;
    }
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    public int getRepFieldsCount() {
      return repFields_.size();
    }
    /**
     * <code>repeated int32 rep_fields = 5 [packed = true];</code>
     *
     * <pre>
     *回复字段顺序
     * </pre>
     */
    public int getRepFields(int index) {
      return repFields_.get(index);
    }
    private int repFieldsMemoizedSerializedSize = -1;

    // repeated .BuyClubList_Reply.GroupData group_list = 6;
    public static final int GROUP_LIST_FIELD_NUMBER = 6;
    private java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData> groupList_;
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    public java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData> getGroupListList() {
      return groupList_;
    }
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    public java.util.List<? extends BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder> 
        getGroupListOrBuilderList() {
      return groupList_;
    }
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    public int getGroupListCount() {
      return groupList_.size();
    }
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    public BuyClubListReply.BuyClubList_Reply.GroupData getGroupList(int index) {
      return groupList_.get(index);
    }
    /**
     * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
     *
     * <pre>
     *group内容列表
     * </pre>
     */
    public BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder getGroupListOrBuilder(
        int index) {
      return groupList_.get(index);
    }

    // required uint32 rep_begin = 7;
    public static final int REP_BEGIN_FIELD_NUMBER = 7;
    private int repBegin_;
    /**
     * <code>required uint32 rep_begin = 7;</code>
     *
     * <pre>
     *起始位置
     * </pre>
     */
    public boolean hasRepBegin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 rep_begin = 7;</code>
     *
     * <pre>
     *起始位置
     * </pre>
     */
    public int getRepBegin() {
      return repBegin_;
    }

    // required uint32 total_size = 8;
    public static final int TOTAL_SIZE_FIELD_NUMBER = 8;
    private int totalSize_;
    /**
     * <code>required uint32 total_size = 8;</code>
     *
     * <pre>
     *总大小
     * </pre>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 total_size = 8;</code>
     *
     * <pre>
     *总大小
     * </pre>
     */
    public int getTotalSize() {
      return totalSize_;
    }

    // required int32 sort_field = 9;
    public static final int SORT_FIELD_FIELD_NUMBER = 9;
    private int sortField_;
    /**
     * <code>required int32 sort_field = 9;</code>
     *
     * <pre>
     *请求的排序字段
     * </pre>
     */
    public boolean hasSortField() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 sort_field = 9;</code>
     *
     * <pre>
     *请求的排序字段
     * </pre>
     */
    public int getSortField() {
      return sortField_;
    }

    // required bool sort_order = 10;
    public static final int SORT_ORDER_FIELD_NUMBER = 10;
    private boolean sortOrder_;
    /**
     * <code>required bool sort_order = 10;</code>
     *
     * <pre>
     *请求的升降序
     * </pre>
     */
    public boolean hasSortOrder() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool sort_order = 10;</code>
     *
     * <pre>
     *请求的升降序
     * </pre>
     */
    public boolean getSortOrder() {
      return sortOrder_;
    }

    // required string icon_url_pre = 11;
    public static final int ICON_URL_PRE_FIELD_NUMBER = 11;
    private java.lang.Object iconUrlPre_;
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    public boolean hasIconUrlPre() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    public java.lang.String getIconUrlPre() {
      java.lang.Object ref = iconUrlPre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          iconUrlPre_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icon_url_pre = 11;</code>
     *
     * <pre>
     *组合图片URL前缀
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconUrlPreBytes() {
      java.lang.Object ref = iconUrlPre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconUrlPre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 req_flag = 12;
    public static final int REQ_FLAG_FIELD_NUMBER = 12;
    private int reqFlag_;
    /**
     * <code>optional uint32 req_flag = 12;</code>
     *
     * <pre>
     *请求标识符
     * </pre>
     */
    public boolean hasReqFlag() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 req_flag = 12;</code>
     *
     * <pre>
     *请求标识符
     * </pre>
     */
    public int getReqFlag() {
      return reqFlag_;
    }

    private void initFields() {
      classType_ = 0;
      repFields_ = java.util.Collections.emptyList();
      groupList_ = java.util.Collections.emptyList();
      repBegin_ = 0;
      totalSize_ = 0;
      sortField_ = 0;
      sortOrder_ = false;
      iconUrlPre_ = "";
      reqFlag_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClassType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRepBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSortField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSortOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIconUrlPre()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGroupListCount(); i++) {
        if (!getGroupList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(4, classType_);
      }
      if (getRepFieldsList().size() > 0) {
        output.writeRawVarint32(42);
        output.writeRawVarint32(repFieldsMemoizedSerializedSize);
      }
      for (int i = 0; i < repFields_.size(); i++) {
        output.writeInt32NoTag(repFields_.get(i));
      }
      for (int i = 0; i < groupList_.size(); i++) {
        output.writeMessage(6, groupList_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(7, repBegin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(8, totalSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(9, sortField_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(10, sortOrder_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(11, getIconUrlPreBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(12, reqFlag_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, classType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < repFields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(repFields_.get(i));
        }
        size += dataSize;
        if (!getRepFieldsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        repFieldsMemoizedSerializedSize = dataSize;
      }
      for (int i = 0; i < groupList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, groupList_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, repBegin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, totalSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, sortField_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, sortOrder_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getIconUrlPreBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, reqFlag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BuyClubListReply.BuyClubList_Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BuyClubListReply.BuyClubList_Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BuyClubListReply.BuyClubList_Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BuyClubListReply.BuyClubList_Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuyClubList_Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BuyClubListReply.BuyClubList_ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BuyClubListReply.internal_static_BuyClubList_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BuyClubListReply.internal_static_BuyClubList_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BuyClubListReply.BuyClubList_Reply.class, BuyClubListReply.BuyClubList_Reply.Builder.class);
      }

      // Construct using BuyClubListReply.BuyClubList_Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGroupListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        classType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        repFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        if (groupListBuilder_ == null) {
          groupList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          groupListBuilder_.clear();
        }
        repBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        totalSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        sortField_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        sortOrder_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        iconUrlPre_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        reqFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BuyClubListReply.internal_static_BuyClubList_Reply_descriptor;
      }

      public BuyClubListReply.BuyClubList_Reply getDefaultInstanceForType() {
        return BuyClubListReply.BuyClubList_Reply.getDefaultInstance();
      }

      public BuyClubListReply.BuyClubList_Reply build() {
        BuyClubListReply.BuyClubList_Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BuyClubListReply.BuyClubList_Reply buildPartial() {
        BuyClubListReply.BuyClubList_Reply result = new BuyClubListReply.BuyClubList_Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.classType_ = classType_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          repFields_ = java.util.Collections.unmodifiableList(repFields_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.repFields_ = repFields_;
        if (groupListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            groupList_ = java.util.Collections.unmodifiableList(groupList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.groupList_ = groupList_;
        } else {
          result.groupList_ = groupListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.repBegin_ = repBegin_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.totalSize_ = totalSize_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sortField_ = sortField_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sortOrder_ = sortOrder_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.iconUrlPre_ = iconUrlPre_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.reqFlag_ = reqFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BuyClubListReply.BuyClubList_Reply) {
          return mergeFrom((BuyClubListReply.BuyClubList_Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BuyClubListReply.BuyClubList_Reply other) {
        if (other == BuyClubListReply.BuyClubList_Reply.getDefaultInstance()) return this;
        if (other.hasClassType()) {
          setClassType(other.getClassType());
        }
        if (!other.repFields_.isEmpty()) {
          if (repFields_.isEmpty()) {
            repFields_ = other.repFields_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRepFieldsIsMutable();
            repFields_.addAll(other.repFields_);
          }
          onChanged();
        }
        if (groupListBuilder_ == null) {
          if (!other.groupList_.isEmpty()) {
            if (groupList_.isEmpty()) {
              groupList_ = other.groupList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGroupListIsMutable();
              groupList_.addAll(other.groupList_);
            }
            onChanged();
          }
        } else {
          if (!other.groupList_.isEmpty()) {
            if (groupListBuilder_.isEmpty()) {
              groupListBuilder_.dispose();
              groupListBuilder_ = null;
              groupList_ = other.groupList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              groupListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGroupListFieldBuilder() : null;
            } else {
              groupListBuilder_.addAllMessages(other.groupList_);
            }
          }
        }
        if (other.hasRepBegin()) {
          setRepBegin(other.getRepBegin());
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasSortField()) {
          setSortField(other.getSortField());
        }
        if (other.hasSortOrder()) {
          setSortOrder(other.getSortOrder());
        }
        if (other.hasIconUrlPre()) {
          bitField0_ |= 0x00000080;
          iconUrlPre_ = other.iconUrlPre_;
          onChanged();
        }
        if (other.hasReqFlag()) {
          setReqFlag(other.getReqFlag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClassType()) {
          
          return false;
        }
        if (!hasRepBegin()) {
          
          return false;
        }
        if (!hasTotalSize()) {
          
          return false;
        }
        if (!hasSortField()) {
          
          return false;
        }
        if (!hasSortOrder()) {
          
          return false;
        }
        if (!hasIconUrlPre()) {
          
          return false;
        }
        for (int i = 0; i < getGroupListCount(); i++) {
          if (!getGroupList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BuyClubListReply.BuyClubList_Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BuyClubListReply.BuyClubList_Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 class_type = 4;
      private int classType_ ;
      /**
       * <code>required int32 class_type = 4;</code>
       *
       * <pre>
       * 0:正常排序列表  1:"我的组合"
       * </pre>
       */
      public boolean hasClassType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 class_type = 4;</code>
       *
       * <pre>
       * 0:正常排序列表  1:"我的组合"
       * </pre>
       */
      public int getClassType() {
        return classType_;
      }
      /**
       * <code>required int32 class_type = 4;</code>
       *
       * <pre>
       * 0:正常排序列表  1:"我的组合"
       * </pre>
       */
      public Builder setClassType(int value) {
        bitField0_ |= 0x00000001;
        classType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 class_type = 4;</code>
       *
       * <pre>
       * 0:正常排序列表  1:"我的组合"
       * </pre>
       */
      public Builder clearClassType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        classType_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 rep_fields = 5 [packed = true];
      private java.util.List<java.lang.Integer> repFields_ = java.util.Collections.emptyList();
      private void ensureRepFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          repFields_ = new java.util.ArrayList<java.lang.Integer>(repFields_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getRepFieldsList() {
        return java.util.Collections.unmodifiableList(repFields_);
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public int getRepFieldsCount() {
        return repFields_.size();
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public int getRepFields(int index) {
        return repFields_.get(index);
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public Builder setRepFields(
          int index, int value) {
        ensureRepFieldsIsMutable();
        repFields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public Builder addRepFields(int value) {
        ensureRepFieldsIsMutable();
        repFields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public Builder addAllRepFields(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureRepFieldsIsMutable();
        super.addAll(values, repFields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 rep_fields = 5 [packed = true];</code>
       *
       * <pre>
       *回复字段顺序
       * </pre>
       */
      public Builder clearRepFields() {
        repFields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated .BuyClubList_Reply.GroupData group_list = 6;
      private java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData> groupList_ =
        java.util.Collections.emptyList();
      private void ensureGroupListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          groupList_ = new java.util.ArrayList<BuyClubListReply.BuyClubList_Reply.GroupData>(groupList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          BuyClubListReply.BuyClubList_Reply.GroupData, BuyClubListReply.BuyClubList_Reply.GroupData.Builder, BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder> groupListBuilder_;

      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData> getGroupListList() {
        if (groupListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groupList_);
        } else {
          return groupListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public int getGroupListCount() {
        if (groupListBuilder_ == null) {
          return groupList_.size();
        } else {
          return groupListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public BuyClubListReply.BuyClubList_Reply.GroupData getGroupList(int index) {
        if (groupListBuilder_ == null) {
          return groupList_.get(index);
        } else {
          return groupListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder setGroupList(
          int index, BuyClubListReply.BuyClubList_Reply.GroupData value) {
        if (groupListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupListIsMutable();
          groupList_.set(index, value);
          onChanged();
        } else {
          groupListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder setGroupList(
          int index, BuyClubListReply.BuyClubList_Reply.GroupData.Builder builderForValue) {
        if (groupListBuilder_ == null) {
          ensureGroupListIsMutable();
          groupList_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder addGroupList(BuyClubListReply.BuyClubList_Reply.GroupData value) {
        if (groupListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupListIsMutable();
          groupList_.add(value);
          onChanged();
        } else {
          groupListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder addGroupList(
          int index, BuyClubListReply.BuyClubList_Reply.GroupData value) {
        if (groupListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupListIsMutable();
          groupList_.add(index, value);
          onChanged();
        } else {
          groupListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder addGroupList(
          BuyClubListReply.BuyClubList_Reply.GroupData.Builder builderForValue) {
        if (groupListBuilder_ == null) {
          ensureGroupListIsMutable();
          groupList_.add(builderForValue.build());
          onChanged();
        } else {
          groupListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder addGroupList(
          int index, BuyClubListReply.BuyClubList_Reply.GroupData.Builder builderForValue) {
        if (groupListBuilder_ == null) {
          ensureGroupListIsMutable();
          groupList_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder addAllGroupList(
          java.lang.Iterable<? extends BuyClubListReply.BuyClubList_Reply.GroupData> values) {
        if (groupListBuilder_ == null) {
          ensureGroupListIsMutable();
          super.addAll(values, groupList_);
          onChanged();
        } else {
          groupListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder clearGroupList() {
        if (groupListBuilder_ == null) {
          groupList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          groupListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public Builder removeGroupList(int index) {
        if (groupListBuilder_ == null) {
          ensureGroupListIsMutable();
          groupList_.remove(index);
          onChanged();
        } else {
          groupListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public BuyClubListReply.BuyClubList_Reply.GroupData.Builder getGroupListBuilder(
          int index) {
        return getGroupListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder getGroupListOrBuilder(
          int index) {
        if (groupListBuilder_ == null) {
          return groupList_.get(index);  } else {
          return groupListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public java.util.List<? extends BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder> 
           getGroupListOrBuilderList() {
        if (groupListBuilder_ != null) {
          return groupListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groupList_);
        }
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public BuyClubListReply.BuyClubList_Reply.GroupData.Builder addGroupListBuilder() {
        return getGroupListFieldBuilder().addBuilder(
            BuyClubListReply.BuyClubList_Reply.GroupData.getDefaultInstance());
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public BuyClubListReply.BuyClubList_Reply.GroupData.Builder addGroupListBuilder(
          int index) {
        return getGroupListFieldBuilder().addBuilder(
            index, BuyClubListReply.BuyClubList_Reply.GroupData.getDefaultInstance());
      }
      /**
       * <code>repeated .BuyClubList_Reply.GroupData group_list = 6;</code>
       *
       * <pre>
       *group内容列表
       * </pre>
       */
      public java.util.List<BuyClubListReply.BuyClubList_Reply.GroupData.Builder> 
           getGroupListBuilderList() {
        return getGroupListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          BuyClubListReply.BuyClubList_Reply.GroupData, BuyClubListReply.BuyClubList_Reply.GroupData.Builder, BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder> 
          getGroupListFieldBuilder() {
        if (groupListBuilder_ == null) {
          groupListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              BuyClubListReply.BuyClubList_Reply.GroupData, BuyClubListReply.BuyClubList_Reply.GroupData.Builder, BuyClubListReply.BuyClubList_Reply.GroupDataOrBuilder>(
                  groupList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          groupList_ = null;
        }
        return groupListBuilder_;
      }

      // required uint32 rep_begin = 7;
      private int repBegin_ ;
      /**
       * <code>required uint32 rep_begin = 7;</code>
       *
       * <pre>
       *起始位置
       * </pre>
       */
      public boolean hasRepBegin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 rep_begin = 7;</code>
       *
       * <pre>
       *起始位置
       * </pre>
       */
      public int getRepBegin() {
        return repBegin_;
      }
      /**
       * <code>required uint32 rep_begin = 7;</code>
       *
       * <pre>
       *起始位置
       * </pre>
       */
      public Builder setRepBegin(int value) {
        bitField0_ |= 0x00000008;
        repBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 rep_begin = 7;</code>
       *
       * <pre>
       *起始位置
       * </pre>
       */
      public Builder clearRepBegin() {
        bitField0_ = (bitField0_ & ~0x00000008);
        repBegin_ = 0;
        onChanged();
        return this;
      }

      // required uint32 total_size = 8;
      private int totalSize_ ;
      /**
       * <code>required uint32 total_size = 8;</code>
       *
       * <pre>
       *总大小
       * </pre>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 total_size = 8;</code>
       *
       * <pre>
       *总大小
       * </pre>
       */
      public int getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>required uint32 total_size = 8;</code>
       *
       * <pre>
       *总大小
       * </pre>
       */
      public Builder setTotalSize(int value) {
        bitField0_ |= 0x00000010;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 total_size = 8;</code>
       *
       * <pre>
       *总大小
       * </pre>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalSize_ = 0;
        onChanged();
        return this;
      }

      // required int32 sort_field = 9;
      private int sortField_ ;
      /**
       * <code>required int32 sort_field = 9;</code>
       *
       * <pre>
       *请求的排序字段
       * </pre>
       */
      public boolean hasSortField() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 sort_field = 9;</code>
       *
       * <pre>
       *请求的排序字段
       * </pre>
       */
      public int getSortField() {
        return sortField_;
      }
      /**
       * <code>required int32 sort_field = 9;</code>
       *
       * <pre>
       *请求的排序字段
       * </pre>
       */
      public Builder setSortField(int value) {
        bitField0_ |= 0x00000020;
        sortField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sort_field = 9;</code>
       *
       * <pre>
       *请求的排序字段
       * </pre>
       */
      public Builder clearSortField() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sortField_ = 0;
        onChanged();
        return this;
      }

      // required bool sort_order = 10;
      private boolean sortOrder_ ;
      /**
       * <code>required bool sort_order = 10;</code>
       *
       * <pre>
       *请求的升降序
       * </pre>
       */
      public boolean hasSortOrder() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bool sort_order = 10;</code>
       *
       * <pre>
       *请求的升降序
       * </pre>
       */
      public boolean getSortOrder() {
        return sortOrder_;
      }
      /**
       * <code>required bool sort_order = 10;</code>
       *
       * <pre>
       *请求的升降序
       * </pre>
       */
      public Builder setSortOrder(boolean value) {
        bitField0_ |= 0x00000040;
        sortOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool sort_order = 10;</code>
       *
       * <pre>
       *请求的升降序
       * </pre>
       */
      public Builder clearSortOrder() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sortOrder_ = false;
        onChanged();
        return this;
      }

      // required string icon_url_pre = 11;
      private java.lang.Object iconUrlPre_ = "";
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public boolean hasIconUrlPre() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public java.lang.String getIconUrlPre() {
        java.lang.Object ref = iconUrlPre_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          iconUrlPre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIconUrlPreBytes() {
        java.lang.Object ref = iconUrlPre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconUrlPre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public Builder setIconUrlPre(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        iconUrlPre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public Builder clearIconUrlPre() {
        bitField0_ = (bitField0_ & ~0x00000080);
        iconUrlPre_ = getDefaultInstance().getIconUrlPre();
        onChanged();
        return this;
      }
      /**
       * <code>required string icon_url_pre = 11;</code>
       *
       * <pre>
       *组合图片URL前缀
       * </pre>
       */
      public Builder setIconUrlPreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        iconUrlPre_ = value;
        onChanged();
        return this;
      }

      // optional uint32 req_flag = 12;
      private int reqFlag_ ;
      /**
       * <code>optional uint32 req_flag = 12;</code>
       *
       * <pre>
       *请求标识符
       * </pre>
       */
      public boolean hasReqFlag() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 req_flag = 12;</code>
       *
       * <pre>
       *请求标识符
       * </pre>
       */
      public int getReqFlag() {
        return reqFlag_;
      }
      /**
       * <code>optional uint32 req_flag = 12;</code>
       *
       * <pre>
       *请求标识符
       * </pre>
       */
      public Builder setReqFlag(int value) {
        bitField0_ |= 0x00000100;
        reqFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 req_flag = 12;</code>
       *
       * <pre>
       *请求标识符
       * </pre>
       */
      public Builder clearReqFlag() {
        bitField0_ = (bitField0_ & ~0x00000100);
        reqFlag_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuyClubList_Reply)
    }

    static {
      defaultInstance = new BuyClubList_Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BuyClubList_Reply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyClubList_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuyClubList_Reply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyClubList_Reply_GroupData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuyClubList_Reply_GroupData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027BuyClubList_Reply.proto\"\257\002\n\021BuyClubLis" +
      "t_Reply\022\022\n\nclass_type\030\004 \002(\005\022\026\n\nrep_field" +
      "s\030\005 \003(\005B\002\020\001\0220\n\ngroup_list\030\006 \003(\0132\034.BuyClu" +
      "bList_Reply.GroupData\022\021\n\trep_begin\030\007 \002(\r" +
      "\022\022\n\ntotal_size\030\010 \002(\r\022\022\n\nsort_field\030\t \002(\005" +
      "\022\022\n\nsort_order\030\n \002(\010\022\024\n\014icon_url_pre\030\013 \002" +
      "(\t\022\020\n\010req_flag\030\014 \001(\r\032E\n\tGroupData\022\020\n\010gro" +
      "up_id\030\001 \002(\r\022\r\n\005state\030\002 \002(\005\022\027\n\017rep_field_" +
      "value\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BuyClubList_Reply_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BuyClubList_Reply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BuyClubList_Reply_descriptor,
              new java.lang.String[] { "ClassType", "RepFields", "GroupList", "RepBegin", "TotalSize", "SortField", "SortOrder", "IconUrlPre", "ReqFlag", });
          internal_static_BuyClubList_Reply_GroupData_descriptor =
            internal_static_BuyClubList_Reply_descriptor.getNestedTypes().get(0);
          internal_static_BuyClubList_Reply_GroupData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BuyClubList_Reply_GroupData_descriptor,
              new java.lang.String[] { "GroupId", "State", "RepFieldValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
