package cn.emoney.acg.data.protocol.motif;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupTrend_Request.proto

public final class GroupTrendRequest {
  private GroupTrendRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GroupTrend_RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 group_code = 1;
    /**
     * <code>required int32 group_code = 1;</code>
     */
    boolean hasGroupCode();
    /**
     * <code>required int32 group_code = 1;</code>
     */
    int getGroupCode();
  }
  /**
   * Protobuf type {@code GroupTrend_Request}
   */
  public static final class GroupTrend_Request extends
      com.google.protobuf.GeneratedMessage
      implements GroupTrend_RequestOrBuilder {
    // Use GroupTrend_Request.newBuilder() to construct.
    private GroupTrend_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupTrend_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupTrend_Request defaultInstance;
    public static GroupTrend_Request getDefaultInstance() {
      return defaultInstance;
    }

    public GroupTrend_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupTrend_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              groupCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GroupTrendRequest.internal_static_GroupTrend_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GroupTrendRequest.internal_static_GroupTrend_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GroupTrendRequest.GroupTrend_Request.class, GroupTrendRequest.GroupTrend_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupTrend_Request> PARSER =
        new com.google.protobuf.AbstractParser<GroupTrend_Request>() {
      public GroupTrend_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupTrend_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupTrend_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 group_code = 1;
    public static final int GROUP_CODE_FIELD_NUMBER = 1;
    private int groupCode_;
    /**
     * <code>required int32 group_code = 1;</code>
     */
    public boolean hasGroupCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 group_code = 1;</code>
     */
    public int getGroupCode() {
      return groupCode_;
    }

    private void initFields() {
      groupCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, groupCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, groupCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GroupTrendRequest.GroupTrend_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GroupTrendRequest.GroupTrend_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GroupTrendRequest.GroupTrend_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GroupTrendRequest.GroupTrend_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GroupTrend_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GroupTrendRequest.GroupTrend_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GroupTrendRequest.internal_static_GroupTrend_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GroupTrendRequest.internal_static_GroupTrend_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GroupTrendRequest.GroupTrend_Request.class, GroupTrendRequest.GroupTrend_Request.Builder.class);
      }

      // Construct using GroupTrendRequest.GroupTrend_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GroupTrendRequest.internal_static_GroupTrend_Request_descriptor;
      }

      public GroupTrendRequest.GroupTrend_Request getDefaultInstanceForType() {
        return GroupTrendRequest.GroupTrend_Request.getDefaultInstance();
      }

      public GroupTrendRequest.GroupTrend_Request build() {
        GroupTrendRequest.GroupTrend_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GroupTrendRequest.GroupTrend_Request buildPartial() {
        GroupTrendRequest.GroupTrend_Request result = new GroupTrendRequest.GroupTrend_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupCode_ = groupCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GroupTrendRequest.GroupTrend_Request) {
          return mergeFrom((GroupTrendRequest.GroupTrend_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GroupTrendRequest.GroupTrend_Request other) {
        if (other == GroupTrendRequest.GroupTrend_Request.getDefaultInstance()) return this;
        if (other.hasGroupCode()) {
          setGroupCode(other.getGroupCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GroupTrendRequest.GroupTrend_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GroupTrendRequest.GroupTrend_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 group_code = 1;
      private int groupCode_ ;
      /**
       * <code>required int32 group_code = 1;</code>
       */
      public boolean hasGroupCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 group_code = 1;</code>
       */
      public int getGroupCode() {
        return groupCode_;
      }
      /**
       * <code>required int32 group_code = 1;</code>
       */
      public Builder setGroupCode(int value) {
        bitField0_ |= 0x00000001;
        groupCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 group_code = 1;</code>
       */
      public Builder clearGroupCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GroupTrend_Request)
    }

    static {
      defaultInstance = new GroupTrend_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GroupTrend_Request)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupTrend_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GroupTrend_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030GroupTrend_Request.proto\"(\n\022GroupTrend" +
      "_Request\022\022\n\ngroup_code\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GroupTrend_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GroupTrend_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GroupTrend_Request_descriptor,
              new java.lang.String[] { "GroupCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
