package cn.emoney.acg.data.protocol.quote;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CandleStick_Request.proto

public final class CandleStickRequest {
  private CandleStickRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CandleStick_RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 goods_id = 1;
    /**
     * <code>required uint32 goods_id = 1;</code>
     *
     * <pre>
     *股票ID
     * </pre>
     */
    boolean hasGoodsId();
    /**
     * <code>required uint32 goods_id = 1;</code>
     *
     * <pre>
     *股票ID
     * </pre>
     */
    int getGoodsId();

    // required uint32 req_begin = 2;
    /**
     * <code>required uint32 req_begin = 2;</code>
     *
     * <pre>
     *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
     * </pre>
     */
    boolean hasReqBegin();
    /**
     * <code>required uint32 req_begin = 2;</code>
     *
     * <pre>
     *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
     * </pre>
     */
    int getReqBegin();

    // required int32 req_size = 3;
    /**
     * <code>required int32 req_size = 3;</code>
     *
     * <pre>
     *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
     * </pre>
     */
    boolean hasReqSize();
    /**
     * <code>required int32 req_size = 3;</code>
     *
     * <pre>
     *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
     * </pre>
     */
    int getReqSize();

    // required uint32 req_period = 5;
    /**
     * <code>required uint32 req_period = 5;</code>
     *
     * <pre>
     *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
     * </pre>
     */
    boolean hasReqPeriod();
    /**
     * <code>required uint32 req_period = 5;</code>
     *
     * <pre>
     *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
     * </pre>
     */
    int getReqPeriod();

    // required uint32 last_update_market_time = 6;
    /**
     * <code>required uint32 last_update_market_time = 6;</code>
     *
     * <pre>
     *上次更新时间，初始填0
     * </pre>
     */
    boolean hasLastUpdateMarketTime();
    /**
     * <code>required uint32 last_update_market_time = 6;</code>
     *
     * <pre>
     *上次更新时间，初始填0
     * </pre>
     */
    int getLastUpdateMarketTime();

    // optional uint32 req_ma = 7 [default = 0];
    /**
     * <code>optional uint32 req_ma = 7 [default = 0];</code>
     */
    boolean hasReqMa();
    /**
     * <code>optional uint32 req_ma = 7 [default = 0];</code>
     */
    int getReqMa();
  }
  /**
   * Protobuf type {@code CandleStick_Request}
   */
  public static final class CandleStick_Request extends
      com.google.protobuf.GeneratedMessage
      implements CandleStick_RequestOrBuilder {
    // Use CandleStick_Request.newBuilder() to construct.
    private CandleStick_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CandleStick_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CandleStick_Request defaultInstance;
    public static CandleStick_Request getDefaultInstance() {
      return defaultInstance;
    }

    public CandleStick_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CandleStick_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              goodsId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              reqBegin_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              reqSize_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              reqPeriod_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              lastUpdateMarketTime_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              reqMa_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CandleStickRequest.internal_static_CandleStick_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CandleStickRequest.internal_static_CandleStick_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CandleStickRequest.CandleStick_Request.class, CandleStickRequest.CandleStick_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<CandleStick_Request> PARSER =
        new com.google.protobuf.AbstractParser<CandleStick_Request>() {
      public CandleStick_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CandleStick_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CandleStick_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 goods_id = 1;
    public static final int GOODS_ID_FIELD_NUMBER = 1;
    private int goodsId_;
    /**
     * <code>required uint32 goods_id = 1;</code>
     *
     * <pre>
     *股票ID
     * </pre>
     */
    public boolean hasGoodsId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 goods_id = 1;</code>
     *
     * <pre>
     *股票ID
     * </pre>
     */
    public int getGoodsId() {
      return goodsId_;
    }

    // required uint32 req_begin = 2;
    public static final int REQ_BEGIN_FIELD_NUMBER = 2;
    private int reqBegin_;
    /**
     * <code>required uint32 req_begin = 2;</code>
     *
     * <pre>
     *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
     * </pre>
     */
    public boolean hasReqBegin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 req_begin = 2;</code>
     *
     * <pre>
     *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
     * </pre>
     */
    public int getReqBegin() {
      return reqBegin_;
    }

    // required int32 req_size = 3;
    public static final int REQ_SIZE_FIELD_NUMBER = 3;
    private int reqSize_;
    /**
     * <code>required int32 req_size = 3;</code>
     *
     * <pre>
     *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
     * </pre>
     */
    public boolean hasReqSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 req_size = 3;</code>
     *
     * <pre>
     *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
     * </pre>
     */
    public int getReqSize() {
      return reqSize_;
    }

    // required uint32 req_period = 5;
    public static final int REQ_PERIOD_FIELD_NUMBER = 5;
    private int reqPeriod_;
    /**
     * <code>required uint32 req_period = 5;</code>
     *
     * <pre>
     *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
     * </pre>
     */
    public boolean hasReqPeriod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 req_period = 5;</code>
     *
     * <pre>
     *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
     * </pre>
     */
    public int getReqPeriod() {
      return reqPeriod_;
    }

    // required uint32 last_update_market_time = 6;
    public static final int LAST_UPDATE_MARKET_TIME_FIELD_NUMBER = 6;
    private int lastUpdateMarketTime_;
    /**
     * <code>required uint32 last_update_market_time = 6;</code>
     *
     * <pre>
     *上次更新时间，初始填0
     * </pre>
     */
    public boolean hasLastUpdateMarketTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 last_update_market_time = 6;</code>
     *
     * <pre>
     *上次更新时间，初始填0
     * </pre>
     */
    public int getLastUpdateMarketTime() {
      return lastUpdateMarketTime_;
    }

    // optional uint32 req_ma = 7 [default = 0];
    public static final int REQ_MA_FIELD_NUMBER = 7;
    private int reqMa_;
    /**
     * <code>optional uint32 req_ma = 7 [default = 0];</code>
     */
    public boolean hasReqMa() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 req_ma = 7 [default = 0];</code>
     */
    public int getReqMa() {
      return reqMa_;
    }

    private void initFields() {
      goodsId_ = 0;
      reqBegin_ = 0;
      reqSize_ = 0;
      reqPeriod_ = 0;
      lastUpdateMarketTime_ = 0;
      reqMa_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGoodsId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqPeriod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastUpdateMarketTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, goodsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, reqBegin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, reqSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, reqPeriod_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(6, lastUpdateMarketTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(7, reqMa_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, goodsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, reqBegin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, reqSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, reqPeriod_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, lastUpdateMarketTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, reqMa_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CandleStickRequest.CandleStick_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CandleStickRequest.CandleStick_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CandleStickRequest.CandleStick_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CandleStickRequest.CandleStick_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CandleStickRequest.CandleStick_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CandleStick_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CandleStickRequest.CandleStick_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CandleStickRequest.internal_static_CandleStick_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CandleStickRequest.internal_static_CandleStick_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CandleStickRequest.CandleStick_Request.class, CandleStickRequest.CandleStick_Request.Builder.class);
      }

      // Construct using CandleStickRequest.CandleStick_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        goodsId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        reqSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        reqPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        lastUpdateMarketTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        reqMa_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CandleStickRequest.internal_static_CandleStick_Request_descriptor;
      }

      public CandleStickRequest.CandleStick_Request getDefaultInstanceForType() {
        return CandleStickRequest.CandleStick_Request.getDefaultInstance();
      }

      public CandleStickRequest.CandleStick_Request build() {
        CandleStickRequest.CandleStick_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CandleStickRequest.CandleStick_Request buildPartial() {
        CandleStickRequest.CandleStick_Request result = new CandleStickRequest.CandleStick_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.goodsId_ = goodsId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqBegin_ = reqBegin_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqSize_ = reqSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reqPeriod_ = reqPeriod_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastUpdateMarketTime_ = lastUpdateMarketTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.reqMa_ = reqMa_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CandleStickRequest.CandleStick_Request) {
          return mergeFrom((CandleStickRequest.CandleStick_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CandleStickRequest.CandleStick_Request other) {
        if (other == CandleStickRequest.CandleStick_Request.getDefaultInstance()) return this;
        if (other.hasGoodsId()) {
          setGoodsId(other.getGoodsId());
        }
        if (other.hasReqBegin()) {
          setReqBegin(other.getReqBegin());
        }
        if (other.hasReqSize()) {
          setReqSize(other.getReqSize());
        }
        if (other.hasReqPeriod()) {
          setReqPeriod(other.getReqPeriod());
        }
        if (other.hasLastUpdateMarketTime()) {
          setLastUpdateMarketTime(other.getLastUpdateMarketTime());
        }
        if (other.hasReqMa()) {
          setReqMa(other.getReqMa());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGoodsId()) {
          
          return false;
        }
        if (!hasReqBegin()) {
          
          return false;
        }
        if (!hasReqSize()) {
          
          return false;
        }
        if (!hasReqPeriod()) {
          
          return false;
        }
        if (!hasLastUpdateMarketTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CandleStickRequest.CandleStick_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CandleStickRequest.CandleStick_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 goods_id = 1;
      private int goodsId_ ;
      /**
       * <code>required uint32 goods_id = 1;</code>
       *
       * <pre>
       *股票ID
       * </pre>
       */
      public boolean hasGoodsId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 goods_id = 1;</code>
       *
       * <pre>
       *股票ID
       * </pre>
       */
      public int getGoodsId() {
        return goodsId_;
      }
      /**
       * <code>required uint32 goods_id = 1;</code>
       *
       * <pre>
       *股票ID
       * </pre>
       */
      public Builder setGoodsId(int value) {
        bitField0_ |= 0x00000001;
        goodsId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 goods_id = 1;</code>
       *
       * <pre>
       *股票ID
       * </pre>
       */
      public Builder clearGoodsId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        goodsId_ = 0;
        onChanged();
        return this;
      }

      // required uint32 req_begin = 2;
      private int reqBegin_ ;
      /**
       * <code>required uint32 req_begin = 2;</code>
       *
       * <pre>
       *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
       * </pre>
       */
      public boolean hasReqBegin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 req_begin = 2;</code>
       *
       * <pre>
       *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
       * </pre>
       */
      public int getReqBegin() {
        return reqBegin_;
      }
      /**
       * <code>required uint32 req_begin = 2;</code>
       *
       * <pre>
       *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
       * </pre>
       */
      public Builder setReqBegin(int value) {
        bitField0_ |= 0x00000002;
        reqBegin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 req_begin = 2;</code>
       *
       * <pre>
       *请求起始位置(日期YYYYMMDD或时间YYMMDDXX, XX表示5分钟序号，从9:30为第一个点)
       * </pre>
       */
      public Builder clearReqBegin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqBegin_ = 0;
        onChanged();
        return this;
      }

      // required int32 req_size = 3;
      private int reqSize_ ;
      /**
       * <code>required int32 req_size = 3;</code>
       *
       * <pre>
       *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
       * </pre>
       */
      public boolean hasReqSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 req_size = 3;</code>
       *
       * <pre>
       *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
       * </pre>
       */
      public int getReqSize() {
        return reqSize_;
      }
      /**
       * <code>required int32 req_size = 3;</code>
       *
       * <pre>
       *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
       * </pre>
       */
      public Builder setReqSize(int value) {
        bitField0_ |= 0x00000004;
        reqSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 req_size = 3;</code>
       *
       * <pre>
       *请求根数 ， &gt; 0 从右往左，&lt; 0从左往右
       * </pre>
       */
      public Builder clearReqSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqSize_ = 0;
        onChanged();
        return this;
      }

      // required uint32 req_period = 5;
      private int reqPeriod_ ;
      /**
       * <code>required uint32 req_period = 5;</code>
       *
       * <pre>
       *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
       * </pre>
       */
      public boolean hasReqPeriod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 req_period = 5;</code>
       *
       * <pre>
       *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
       * </pre>
       */
      public int getReqPeriod() {
        return reqPeriod_;
      }
      /**
       * <code>required uint32 req_period = 5;</code>
       *
       * <pre>
       *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
       * </pre>
       */
      public Builder setReqPeriod(int value) {
        bitField0_ |= 0x00000008;
        reqPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 req_period = 5;</code>
       *
       * <pre>
       *周期 &lt;=60  为分钟线，如60分钟线即为60 , 30分钟线即为30 ；日K线100、周K线101、月K线102
       * </pre>
       */
      public Builder clearReqPeriod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reqPeriod_ = 0;
        onChanged();
        return this;
      }

      // required uint32 last_update_market_time = 6;
      private int lastUpdateMarketTime_ ;
      /**
       * <code>required uint32 last_update_market_time = 6;</code>
       *
       * <pre>
       *上次更新时间，初始填0
       * </pre>
       */
      public boolean hasLastUpdateMarketTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 last_update_market_time = 6;</code>
       *
       * <pre>
       *上次更新时间，初始填0
       * </pre>
       */
      public int getLastUpdateMarketTime() {
        return lastUpdateMarketTime_;
      }
      /**
       * <code>required uint32 last_update_market_time = 6;</code>
       *
       * <pre>
       *上次更新时间，初始填0
       * </pre>
       */
      public Builder setLastUpdateMarketTime(int value) {
        bitField0_ |= 0x00000010;
        lastUpdateMarketTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 last_update_market_time = 6;</code>
       *
       * <pre>
       *上次更新时间，初始填0
       * </pre>
       */
      public Builder clearLastUpdateMarketTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastUpdateMarketTime_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 req_ma = 7 [default = 0];
      private int reqMa_ ;
      /**
       * <code>optional uint32 req_ma = 7 [default = 0];</code>
       */
      public boolean hasReqMa() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 req_ma = 7 [default = 0];</code>
       */
      public int getReqMa() {
        return reqMa_;
      }
      /**
       * <code>optional uint32 req_ma = 7 [default = 0];</code>
       */
      public Builder setReqMa(int value) {
        bitField0_ |= 0x00000020;
        reqMa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 req_ma = 7 [default = 0];</code>
       */
      public Builder clearReqMa() {
        bitField0_ = (bitField0_ & ~0x00000020);
        reqMa_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CandleStick_Request)
    }

    static {
      defaultInstance = new CandleStick_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CandleStick_Request)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CandleStick_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CandleStick_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CandleStick_Request.proto\"\224\001\n\023CandleSt" +
      "ick_Request\022\020\n\010goods_id\030\001 \002(\r\022\021\n\treq_beg" +
      "in\030\002 \002(\r\022\020\n\010req_size\030\003 \002(\005\022\022\n\nreq_period" +
      "\030\005 \002(\r\022\037\n\027last_update_market_time\030\006 \002(\r\022" +
      "\021\n\006req_ma\030\007 \001(\r:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CandleStick_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CandleStick_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CandleStick_Request_descriptor,
              new java.lang.String[] { "GoodsId", "ReqBegin", "ReqSize", "ReqPeriod", "LastUpdateMarketTime", "ReqMa", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
