package cn.emoney.acg.data.protocol.quote;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cpx_Reply.proto

public final class CpxReply {
  private CpxReply() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Cpx_ReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Cpx_Reply.cpx_item cpx_item_array = 1;
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    java.util.List<CpxReply.Cpx_Reply.cpx_item> 
        getCpxItemArrayList();
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    CpxReply.Cpx_Reply.cpx_item getCpxItemArray(int index);
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    int getCpxItemArrayCount();
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    java.util.List<? extends CpxReply.Cpx_Reply.cpx_itemOrBuilder> 
        getCpxItemArrayOrBuilderList();
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    CpxReply.Cpx_Reply.cpx_itemOrBuilder getCpxItemArrayOrBuilder(
        int index);

    // required uint32 update_market_time = 2;
    /**
     * <code>required uint32 update_market_time = 2;</code>
     *
     * <pre>
     *更新时间
     * </pre>
     */
    boolean hasUpdateMarketTime();
    /**
     * <code>required uint32 update_market_time = 2;</code>
     *
     * <pre>
     *更新时间
     * </pre>
     */
    int getUpdateMarketTime();
  }
  /**
   * Protobuf type {@code Cpx_Reply}
   */
  public static final class Cpx_Reply extends
      com.google.protobuf.GeneratedMessage
      implements Cpx_ReplyOrBuilder {
    // Use Cpx_Reply.newBuilder() to construct.
    private Cpx_Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cpx_Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cpx_Reply defaultInstance;
    public static Cpx_Reply getDefaultInstance() {
      return defaultInstance;
    }

    public Cpx_Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cpx_Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cpxItemArray_ = new java.util.ArrayList<CpxReply.Cpx_Reply.cpx_item>();
                mutable_bitField0_ |= 0x00000001;
              }
              cpxItemArray_.add(input.readMessage(CpxReply.Cpx_Reply.cpx_item.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              updateMarketTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cpxItemArray_ = java.util.Collections.unmodifiableList(cpxItemArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CpxReply.internal_static_Cpx_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CpxReply.internal_static_Cpx_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CpxReply.Cpx_Reply.class, CpxReply.Cpx_Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<Cpx_Reply> PARSER =
        new com.google.protobuf.AbstractParser<Cpx_Reply>() {
      public Cpx_Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cpx_Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cpx_Reply> getParserForType() {
      return PARSER;
    }

    public interface cpx_itemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required uint32 datetime = 1;
      /**
       * <code>required uint32 datetime = 1;</code>
       *
       * <pre>
       * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
       * </pre>
       */
      boolean hasDatetime();
      /**
       * <code>required uint32 datetime = 1;</code>
       *
       * <pre>
       * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
       * </pre>
       */
      int getDatetime();

      // required string bs_flag = 2;
      /**
       * <code>required string bs_flag = 2;</code>
       */
      boolean hasBsFlag();
      /**
       * <code>required string bs_flag = 2;</code>
       */
      java.lang.String getBsFlag();
      /**
       * <code>required string bs_flag = 2;</code>
       */
      com.google.protobuf.ByteString
          getBsFlagBytes();
    }
    /**
     * Protobuf type {@code Cpx_Reply.cpx_item}
     */
    public static final class cpx_item extends
        com.google.protobuf.GeneratedMessage
        implements cpx_itemOrBuilder {
      // Use cpx_item.newBuilder() to construct.
      private cpx_item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private cpx_item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final cpx_item defaultInstance;
      public static cpx_item getDefaultInstance() {
        return defaultInstance;
      }

      public cpx_item getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private cpx_item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                datetime_ = input.readUInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                bsFlag_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CpxReply.internal_static_Cpx_Reply_cpx_item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CpxReply.internal_static_Cpx_Reply_cpx_item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CpxReply.Cpx_Reply.cpx_item.class, CpxReply.Cpx_Reply.cpx_item.Builder.class);
      }

      public static com.google.protobuf.Parser<cpx_item> PARSER =
          new com.google.protobuf.AbstractParser<cpx_item>() {
        public cpx_item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new cpx_item(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<cpx_item> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required uint32 datetime = 1;
      public static final int DATETIME_FIELD_NUMBER = 1;
      private int datetime_;
      /**
       * <code>required uint32 datetime = 1;</code>
       *
       * <pre>
       * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
       * </pre>
       */
      public boolean hasDatetime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 datetime = 1;</code>
       *
       * <pre>
       * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
       * </pre>
       */
      public int getDatetime() {
        return datetime_;
      }

      // required string bs_flag = 2;
      public static final int BS_FLAG_FIELD_NUMBER = 2;
      private java.lang.Object bsFlag_;
      /**
       * <code>required string bs_flag = 2;</code>
       */
      public boolean hasBsFlag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string bs_flag = 2;</code>
       */
      public java.lang.String getBsFlag() {
        java.lang.Object ref = bsFlag_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bsFlag_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string bs_flag = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBsFlagBytes() {
        java.lang.Object ref = bsFlag_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bsFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        datetime_ = 0;
        bsFlag_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasDatetime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBsFlag()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, datetime_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getBsFlagBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, datetime_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getBsFlagBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CpxReply.Cpx_Reply.cpx_item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(CpxReply.Cpx_Reply.cpx_item prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Cpx_Reply.cpx_item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements CpxReply.Cpx_Reply.cpx_itemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CpxReply.internal_static_Cpx_Reply_cpx_item_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CpxReply.internal_static_Cpx_Reply_cpx_item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CpxReply.Cpx_Reply.cpx_item.class, CpxReply.Cpx_Reply.cpx_item.Builder.class);
        }

        // Construct using CpxReply.Cpx_Reply.cpx_item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          datetime_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          bsFlag_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CpxReply.internal_static_Cpx_Reply_cpx_item_descriptor;
        }

        public CpxReply.Cpx_Reply.cpx_item getDefaultInstanceForType() {
          return CpxReply.Cpx_Reply.cpx_item.getDefaultInstance();
        }

        public CpxReply.Cpx_Reply.cpx_item build() {
          CpxReply.Cpx_Reply.cpx_item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public CpxReply.Cpx_Reply.cpx_item buildPartial() {
          CpxReply.Cpx_Reply.cpx_item result = new CpxReply.Cpx_Reply.cpx_item(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.datetime_ = datetime_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.bsFlag_ = bsFlag_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CpxReply.Cpx_Reply.cpx_item) {
            return mergeFrom((CpxReply.Cpx_Reply.cpx_item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CpxReply.Cpx_Reply.cpx_item other) {
          if (other == CpxReply.Cpx_Reply.cpx_item.getDefaultInstance()) return this;
          if (other.hasDatetime()) {
            setDatetime(other.getDatetime());
          }
          if (other.hasBsFlag()) {
            bitField0_ |= 0x00000002;
            bsFlag_ = other.bsFlag_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDatetime()) {
            
            return false;
          }
          if (!hasBsFlag()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CpxReply.Cpx_Reply.cpx_item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CpxReply.Cpx_Reply.cpx_item) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required uint32 datetime = 1;
        private int datetime_ ;
        /**
         * <code>required uint32 datetime = 1;</code>
         *
         * <pre>
         * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
         * </pre>
         */
        public boolean hasDatetime() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 datetime = 1;</code>
         *
         * <pre>
         * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
         * </pre>
         */
        public int getDatetime() {
          return datetime_;
        }
        /**
         * <code>required uint32 datetime = 1;</code>
         *
         * <pre>
         * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
         * </pre>
         */
        public Builder setDatetime(int value) {
          bitField0_ |= 0x00000001;
          datetime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 datetime = 1;</code>
         *
         * <pre>
         * 日期时间，日线：YYYYMMDD，分时：YYMMDDxxx
         * </pre>
         */
        public Builder clearDatetime() {
          bitField0_ = (bitField0_ & ~0x00000001);
          datetime_ = 0;
          onChanged();
          return this;
        }

        // required string bs_flag = 2;
        private java.lang.Object bsFlag_ = "";
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public boolean hasBsFlag() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public java.lang.String getBsFlag() {
          java.lang.Object ref = bsFlag_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            bsFlag_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public com.google.protobuf.ByteString
            getBsFlagBytes() {
          java.lang.Object ref = bsFlag_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            bsFlag_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public Builder setBsFlag(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          bsFlag_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public Builder clearBsFlag() {
          bitField0_ = (bitField0_ & ~0x00000002);
          bsFlag_ = getDefaultInstance().getBsFlag();
          onChanged();
          return this;
        }
        /**
         * <code>required string bs_flag = 2;</code>
         */
        public Builder setBsFlagBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          bsFlag_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Cpx_Reply.cpx_item)
      }

      static {
        defaultInstance = new cpx_item(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Cpx_Reply.cpx_item)
    }

    private int bitField0_;
    // repeated .Cpx_Reply.cpx_item cpx_item_array = 1;
    public static final int CPX_ITEM_ARRAY_FIELD_NUMBER = 1;
    private java.util.List<CpxReply.Cpx_Reply.cpx_item> cpxItemArray_;
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    public java.util.List<CpxReply.Cpx_Reply.cpx_item> getCpxItemArrayList() {
      return cpxItemArray_;
    }
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    public java.util.List<? extends CpxReply.Cpx_Reply.cpx_itemOrBuilder> 
        getCpxItemArrayOrBuilderList() {
      return cpxItemArray_;
    }
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    public int getCpxItemArrayCount() {
      return cpxItemArray_.size();
    }
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    public CpxReply.Cpx_Reply.cpx_item getCpxItemArray(int index) {
      return cpxItemArray_.get(index);
    }
    /**
     * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
     *
     * <pre>
     *k线数组
     * </pre>
     */
    public CpxReply.Cpx_Reply.cpx_itemOrBuilder getCpxItemArrayOrBuilder(
        int index) {
      return cpxItemArray_.get(index);
    }

    // required uint32 update_market_time = 2;
    public static final int UPDATE_MARKET_TIME_FIELD_NUMBER = 2;
    private int updateMarketTime_;
    /**
     * <code>required uint32 update_market_time = 2;</code>
     *
     * <pre>
     *更新时间
     * </pre>
     */
    public boolean hasUpdateMarketTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 update_market_time = 2;</code>
     *
     * <pre>
     *更新时间
     * </pre>
     */
    public int getUpdateMarketTime() {
      return updateMarketTime_;
    }

    private void initFields() {
      cpxItemArray_ = java.util.Collections.emptyList();
      updateMarketTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUpdateMarketTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCpxItemArrayCount(); i++) {
        if (!getCpxItemArray(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < cpxItemArray_.size(); i++) {
        output.writeMessage(1, cpxItemArray_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(2, updateMarketTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cpxItemArray_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cpxItemArray_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, updateMarketTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CpxReply.Cpx_Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CpxReply.Cpx_Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CpxReply.Cpx_Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CpxReply.Cpx_Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CpxReply.Cpx_Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CpxReply.Cpx_Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CpxReply.Cpx_Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CpxReply.Cpx_Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CpxReply.Cpx_Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CpxReply.Cpx_Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CpxReply.Cpx_Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Cpx_Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CpxReply.Cpx_ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CpxReply.internal_static_Cpx_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CpxReply.internal_static_Cpx_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CpxReply.Cpx_Reply.class, CpxReply.Cpx_Reply.Builder.class);
      }

      // Construct using CpxReply.Cpx_Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCpxItemArrayFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cpxItemArrayBuilder_ == null) {
          cpxItemArray_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cpxItemArrayBuilder_.clear();
        }
        updateMarketTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CpxReply.internal_static_Cpx_Reply_descriptor;
      }

      public CpxReply.Cpx_Reply getDefaultInstanceForType() {
        return CpxReply.Cpx_Reply.getDefaultInstance();
      }

      public CpxReply.Cpx_Reply build() {
        CpxReply.Cpx_Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CpxReply.Cpx_Reply buildPartial() {
        CpxReply.Cpx_Reply result = new CpxReply.Cpx_Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cpxItemArrayBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cpxItemArray_ = java.util.Collections.unmodifiableList(cpxItemArray_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cpxItemArray_ = cpxItemArray_;
        } else {
          result.cpxItemArray_ = cpxItemArrayBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.updateMarketTime_ = updateMarketTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CpxReply.Cpx_Reply) {
          return mergeFrom((CpxReply.Cpx_Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CpxReply.Cpx_Reply other) {
        if (other == CpxReply.Cpx_Reply.getDefaultInstance()) return this;
        if (cpxItemArrayBuilder_ == null) {
          if (!other.cpxItemArray_.isEmpty()) {
            if (cpxItemArray_.isEmpty()) {
              cpxItemArray_ = other.cpxItemArray_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCpxItemArrayIsMutable();
              cpxItemArray_.addAll(other.cpxItemArray_);
            }
            onChanged();
          }
        } else {
          if (!other.cpxItemArray_.isEmpty()) {
            if (cpxItemArrayBuilder_.isEmpty()) {
              cpxItemArrayBuilder_.dispose();
              cpxItemArrayBuilder_ = null;
              cpxItemArray_ = other.cpxItemArray_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cpxItemArrayBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCpxItemArrayFieldBuilder() : null;
            } else {
              cpxItemArrayBuilder_.addAllMessages(other.cpxItemArray_);
            }
          }
        }
        if (other.hasUpdateMarketTime()) {
          setUpdateMarketTime(other.getUpdateMarketTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUpdateMarketTime()) {
          
          return false;
        }
        for (int i = 0; i < getCpxItemArrayCount(); i++) {
          if (!getCpxItemArray(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CpxReply.Cpx_Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CpxReply.Cpx_Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Cpx_Reply.cpx_item cpx_item_array = 1;
      private java.util.List<CpxReply.Cpx_Reply.cpx_item> cpxItemArray_ =
        java.util.Collections.emptyList();
      private void ensureCpxItemArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cpxItemArray_ = new java.util.ArrayList<CpxReply.Cpx_Reply.cpx_item>(cpxItemArray_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CpxReply.Cpx_Reply.cpx_item, CpxReply.Cpx_Reply.cpx_item.Builder, CpxReply.Cpx_Reply.cpx_itemOrBuilder> cpxItemArrayBuilder_;

      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public java.util.List<CpxReply.Cpx_Reply.cpx_item> getCpxItemArrayList() {
        if (cpxItemArrayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cpxItemArray_);
        } else {
          return cpxItemArrayBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public int getCpxItemArrayCount() {
        if (cpxItemArrayBuilder_ == null) {
          return cpxItemArray_.size();
        } else {
          return cpxItemArrayBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public CpxReply.Cpx_Reply.cpx_item getCpxItemArray(int index) {
        if (cpxItemArrayBuilder_ == null) {
          return cpxItemArray_.get(index);
        } else {
          return cpxItemArrayBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder setCpxItemArray(
          int index, CpxReply.Cpx_Reply.cpx_item value) {
        if (cpxItemArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.set(index, value);
          onChanged();
        } else {
          cpxItemArrayBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder setCpxItemArray(
          int index, CpxReply.Cpx_Reply.cpx_item.Builder builderForValue) {
        if (cpxItemArrayBuilder_ == null) {
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.set(index, builderForValue.build());
          onChanged();
        } else {
          cpxItemArrayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder addCpxItemArray(CpxReply.Cpx_Reply.cpx_item value) {
        if (cpxItemArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.add(value);
          onChanged();
        } else {
          cpxItemArrayBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder addCpxItemArray(
          int index, CpxReply.Cpx_Reply.cpx_item value) {
        if (cpxItemArrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.add(index, value);
          onChanged();
        } else {
          cpxItemArrayBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder addCpxItemArray(
          CpxReply.Cpx_Reply.cpx_item.Builder builderForValue) {
        if (cpxItemArrayBuilder_ == null) {
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.add(builderForValue.build());
          onChanged();
        } else {
          cpxItemArrayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder addCpxItemArray(
          int index, CpxReply.Cpx_Reply.cpx_item.Builder builderForValue) {
        if (cpxItemArrayBuilder_ == null) {
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.add(index, builderForValue.build());
          onChanged();
        } else {
          cpxItemArrayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder addAllCpxItemArray(
          java.lang.Iterable<? extends CpxReply.Cpx_Reply.cpx_item> values) {
        if (cpxItemArrayBuilder_ == null) {
          ensureCpxItemArrayIsMutable();
          super.addAll(values, cpxItemArray_);
          onChanged();
        } else {
          cpxItemArrayBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder clearCpxItemArray() {
        if (cpxItemArrayBuilder_ == null) {
          cpxItemArray_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cpxItemArrayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public Builder removeCpxItemArray(int index) {
        if (cpxItemArrayBuilder_ == null) {
          ensureCpxItemArrayIsMutable();
          cpxItemArray_.remove(index);
          onChanged();
        } else {
          cpxItemArrayBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public CpxReply.Cpx_Reply.cpx_item.Builder getCpxItemArrayBuilder(
          int index) {
        return getCpxItemArrayFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public CpxReply.Cpx_Reply.cpx_itemOrBuilder getCpxItemArrayOrBuilder(
          int index) {
        if (cpxItemArrayBuilder_ == null) {
          return cpxItemArray_.get(index);  } else {
          return cpxItemArrayBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public java.util.List<? extends CpxReply.Cpx_Reply.cpx_itemOrBuilder> 
           getCpxItemArrayOrBuilderList() {
        if (cpxItemArrayBuilder_ != null) {
          return cpxItemArrayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cpxItemArray_);
        }
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public CpxReply.Cpx_Reply.cpx_item.Builder addCpxItemArrayBuilder() {
        return getCpxItemArrayFieldBuilder().addBuilder(
            CpxReply.Cpx_Reply.cpx_item.getDefaultInstance());
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public CpxReply.Cpx_Reply.cpx_item.Builder addCpxItemArrayBuilder(
          int index) {
        return getCpxItemArrayFieldBuilder().addBuilder(
            index, CpxReply.Cpx_Reply.cpx_item.getDefaultInstance());
      }
      /**
       * <code>repeated .Cpx_Reply.cpx_item cpx_item_array = 1;</code>
       *
       * <pre>
       *k线数组
       * </pre>
       */
      public java.util.List<CpxReply.Cpx_Reply.cpx_item.Builder> 
           getCpxItemArrayBuilderList() {
        return getCpxItemArrayFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CpxReply.Cpx_Reply.cpx_item, CpxReply.Cpx_Reply.cpx_item.Builder, CpxReply.Cpx_Reply.cpx_itemOrBuilder> 
          getCpxItemArrayFieldBuilder() {
        if (cpxItemArrayBuilder_ == null) {
          cpxItemArrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CpxReply.Cpx_Reply.cpx_item, CpxReply.Cpx_Reply.cpx_item.Builder, CpxReply.Cpx_Reply.cpx_itemOrBuilder>(
                  cpxItemArray_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cpxItemArray_ = null;
        }
        return cpxItemArrayBuilder_;
      }

      // required uint32 update_market_time = 2;
      private int updateMarketTime_ ;
      /**
       * <code>required uint32 update_market_time = 2;</code>
       *
       * <pre>
       *更新时间
       * </pre>
       */
      public boolean hasUpdateMarketTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 update_market_time = 2;</code>
       *
       * <pre>
       *更新时间
       * </pre>
       */
      public int getUpdateMarketTime() {
        return updateMarketTime_;
      }
      /**
       * <code>required uint32 update_market_time = 2;</code>
       *
       * <pre>
       *更新时间
       * </pre>
       */
      public Builder setUpdateMarketTime(int value) {
        bitField0_ |= 0x00000002;
        updateMarketTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 update_market_time = 2;</code>
       *
       * <pre>
       *更新时间
       * </pre>
       */
      public Builder clearUpdateMarketTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        updateMarketTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Cpx_Reply)
    }

    static {
      defaultInstance = new Cpx_Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Cpx_Reply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cpx_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cpx_Reply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Cpx_Reply_cpx_item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Cpx_Reply_cpx_item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Cpx_Reply.proto\"\203\001\n\tCpx_Reply\022+\n\016cpx_i" +
      "tem_array\030\001 \003(\0132\023.Cpx_Reply.cpx_item\022\032\n\022" +
      "update_market_time\030\002 \002(\r\032-\n\010cpx_item\022\020\n\010" +
      "datetime\030\001 \002(\r\022\017\n\007bs_flag\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Cpx_Reply_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Cpx_Reply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cpx_Reply_descriptor,
              new java.lang.String[] { "CpxItemArray", "UpdateMarketTime", });
          internal_static_Cpx_Reply_cpx_item_descriptor =
            internal_static_Cpx_Reply_descriptor.getNestedTypes().get(0);
          internal_static_Cpx_Reply_cpx_item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Cpx_Reply_cpx_item_descriptor,
              new java.lang.String[] { "Datetime", "BsFlag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
