package cn.emoney.acg.data.protocol.quiz;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuizRequire_Reply.proto

public final class QuizRequireReply {
  private QuizRequireReply() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QuizRequire_ReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .quiz.Result result = 1;
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    QuizDefine.Result getResult();
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    QuizDefine.ResultOrBuilder getResultOrBuilder();

    // optional uint64 id = 2 [default = 0];
    /**
     * <code>optional uint64 id = 2 [default = 0];</code>
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 2 [default = 0];</code>
     */
    long getId();

    // optional int32 status = 3 [default = 0];
    /**
     * <code>optional int32 status = 3 [default = 0];</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3 [default = 0];</code>
     */
    int getStatus();

    // optional uint32 commit_time = 4 [default = 0];
    /**
     * <code>optional uint32 commit_time = 4 [default = 0];</code>
     */
    boolean hasCommitTime();
    /**
     * <code>optional uint32 commit_time = 4 [default = 0];</code>
     */
    int getCommitTime();
  }
  /**
   * Protobuf type {@code quiz.QuizRequire_Reply}
   */
  public static final class QuizRequire_Reply extends
      com.google.protobuf.GeneratedMessage
      implements QuizRequire_ReplyOrBuilder {
    // Use QuizRequire_Reply.newBuilder() to construct.
    private QuizRequire_Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QuizRequire_Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QuizRequire_Reply defaultInstance;
    public static QuizRequire_Reply getDefaultInstance() {
      return defaultInstance;
    }

    public QuizRequire_Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QuizRequire_Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              QuizDefine.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(QuizDefine.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              commitTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QuizRequireReply.internal_static_quiz_QuizRequire_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QuizRequireReply.internal_static_quiz_QuizRequire_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuizRequireReply.QuizRequire_Reply.class, QuizRequireReply.QuizRequire_Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<QuizRequire_Reply> PARSER =
        new com.google.protobuf.AbstractParser<QuizRequire_Reply>() {
      public QuizRequire_Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuizRequire_Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QuizRequire_Reply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .quiz.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private QuizDefine.Result result_;
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public QuizDefine.Result getResult() {
      return result_;
    }
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public QuizDefine.ResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    // optional uint64 id = 2 [default = 0];
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>optional uint64 id = 2 [default = 0];</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 id = 2 [default = 0];</code>
     */
    public long getId() {
      return id_;
    }

    // optional int32 status = 3 [default = 0];
    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional int32 status = 3 [default = 0];</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 status = 3 [default = 0];</code>
     */
    public int getStatus() {
      return status_;
    }

    // optional uint32 commit_time = 4 [default = 0];
    public static final int COMMIT_TIME_FIELD_NUMBER = 4;
    private int commitTime_;
    /**
     * <code>optional uint32 commit_time = 4 [default = 0];</code>
     */
    public boolean hasCommitTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 commit_time = 4 [default = 0];</code>
     */
    public int getCommitTime() {
      return commitTime_;
    }

    private void initFields() {
      result_ = QuizDefine.Result.getDefaultInstance();
      id_ = 0L;
      status_ = 0;
      commitTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, commitTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, commitTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QuizRequireReply.QuizRequire_Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QuizRequireReply.QuizRequire_Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QuizRequireReply.QuizRequire_Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QuizRequireReply.QuizRequire_Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quiz.QuizRequire_Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QuizRequireReply.QuizRequire_ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QuizRequireReply.internal_static_quiz_QuizRequire_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QuizRequireReply.internal_static_quiz_QuizRequire_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QuizRequireReply.QuizRequire_Reply.class, QuizRequireReply.QuizRequire_Reply.Builder.class);
      }

      // Construct using QuizRequireReply.QuizRequire_Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = QuizDefine.Result.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        commitTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QuizRequireReply.internal_static_quiz_QuizRequire_Reply_descriptor;
      }

      public QuizRequireReply.QuizRequire_Reply getDefaultInstanceForType() {
        return QuizRequireReply.QuizRequire_Reply.getDefaultInstance();
      }

      public QuizRequireReply.QuizRequire_Reply build() {
        QuizRequireReply.QuizRequire_Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QuizRequireReply.QuizRequire_Reply buildPartial() {
        QuizRequireReply.QuizRequire_Reply result = new QuizRequireReply.QuizRequire_Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.commitTime_ = commitTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QuizRequireReply.QuizRequire_Reply) {
          return mergeFrom((QuizRequireReply.QuizRequire_Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QuizRequireReply.QuizRequire_Reply other) {
        if (other == QuizRequireReply.QuizRequire_Reply.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasCommitTime()) {
          setCommitTime(other.getCommitTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!getResult().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QuizRequireReply.QuizRequire_Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QuizRequireReply.QuizRequire_Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .quiz.Result result = 1;
      private QuizDefine.Result result_ = QuizDefine.Result.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder> resultBuilder_;
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.Result getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder setResult(QuizDefine.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder setResult(
          QuizDefine.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder mergeResult(QuizDefine.Result value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              result_ != QuizDefine.Result.getDefaultInstance()) {
            result_ =
              QuizDefine.Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = QuizDefine.Result.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.Result.Builder getResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // optional uint64 id = 2 [default = 0];
      private long id_ ;
      /**
       * <code>optional uint64 id = 2 [default = 0];</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 id = 2 [default = 0];</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 2 [default = 0];</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 2 [default = 0];</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 status = 3 [default = 0];
      private int status_ ;
      /**
       * <code>optional int32 status = 3 [default = 0];</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 status = 3 [default = 0];</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 3 [default = 0];</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 3 [default = 0];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 commit_time = 4 [default = 0];
      private int commitTime_ ;
      /**
       * <code>optional uint32 commit_time = 4 [default = 0];</code>
       */
      public boolean hasCommitTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 commit_time = 4 [default = 0];</code>
       */
      public int getCommitTime() {
        return commitTime_;
      }
      /**
       * <code>optional uint32 commit_time = 4 [default = 0];</code>
       */
      public Builder setCommitTime(int value) {
        bitField0_ |= 0x00000008;
        commitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 commit_time = 4 [default = 0];</code>
       */
      public Builder clearCommitTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        commitTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:quiz.QuizRequire_Reply)
    }

    static {
      defaultInstance = new QuizRequire_Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:quiz.QuizRequire_Reply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quiz_QuizRequire_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quiz_QuizRequire_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027QuizRequire_Reply.proto\022\004quiz\032\020QuizDef" +
      "ine.proto\"k\n\021QuizRequire_Reply\022\034\n\006result" +
      "\030\001 \002(\0132\014.quiz.Result\022\r\n\002id\030\002 \001(\004:\0010\022\021\n\006s" +
      "tatus\030\003 \001(\005:\0010\022\026\n\013commit_time\030\004 \001(\r:\0010B\002" +
      "\n\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quiz_QuizRequire_Reply_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quiz_QuizRequire_Reply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quiz_QuizRequire_Reply_descriptor,
              new java.lang.String[] { "Result", "Id", "Status", "CommitTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QuizDefine.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
