package cn.emoney.acg.data.protocol.quiz;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuizAnswer_Request.proto

public final class QuizAnswerRequest {
  private QuizAnswerRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QuizAnswer_RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string token_id = 1;
    /**
     * <code>required string token_id = 1;</code>
     */
    boolean hasTokenId();
    /**
     * <code>required string token_id = 1;</code>
     */
    java.lang.String getTokenId();
    /**
     * <code>required string token_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenIdBytes();

    // required uint64 id = 2;
    /**
     * <code>required uint64 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 2;</code>
     */
    long getId();

    // required .quiz.Answer answer = 3;
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    boolean hasAnswer();
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    QuizDefine.Answer getAnswer();
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    QuizDefine.AnswerOrBuilder getAnswerOrBuilder();

    // optional string stocks = 5 [default = ""];
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    boolean hasStocks();
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    java.lang.String getStocks();
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getStocksBytes();
  }
  /**
   * Protobuf type {@code quiz.QuizAnswer_Request}
   */
  public static final class QuizAnswer_Request extends
      com.google.protobuf.GeneratedMessage
      implements QuizAnswer_RequestOrBuilder {
    // Use QuizAnswer_Request.newBuilder() to construct.
    private QuizAnswer_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QuizAnswer_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QuizAnswer_Request defaultInstance;
    public static QuizAnswer_Request getDefaultInstance() {
      return defaultInstance;
    }

    public QuizAnswer_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QuizAnswer_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tokenId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt64();
              break;
            }
            case 26: {
              QuizDefine.Answer.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = answer_.toBuilder();
              }
              answer_ = input.readMessage(QuizDefine.Answer.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(answer_);
                answer_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              stocks_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QuizAnswerRequest.internal_static_quiz_QuizAnswer_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QuizAnswerRequest.internal_static_quiz_QuizAnswer_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QuizAnswerRequest.QuizAnswer_Request.class, QuizAnswerRequest.QuizAnswer_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<QuizAnswer_Request> PARSER =
        new com.google.protobuf.AbstractParser<QuizAnswer_Request>() {
      public QuizAnswer_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuizAnswer_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QuizAnswer_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string token_id = 1;
    public static final int TOKEN_ID_FIELD_NUMBER = 1;
    private java.lang.Object tokenId_;
    /**
     * <code>required string token_id = 1;</code>
     */
    public boolean hasTokenId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token_id = 1;</code>
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>required uint64 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    // required .quiz.Answer answer = 3;
    public static final int ANSWER_FIELD_NUMBER = 3;
    private QuizDefine.Answer answer_;
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    public QuizDefine.Answer getAnswer() {
      return answer_;
    }
    /**
     * <code>required .quiz.Answer answer = 3;</code>
     */
    public QuizDefine.AnswerOrBuilder getAnswerOrBuilder() {
      return answer_;
    }

    // optional string stocks = 5 [default = ""];
    public static final int STOCKS_FIELD_NUMBER = 5;
    private java.lang.Object stocks_;
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    public boolean hasStocks() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    public java.lang.String getStocks() {
      java.lang.Object ref = stocks_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stocks_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stocks = 5 [default = ""];</code>
     *
     * <pre>
     * 关联的股票ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStocksBytes() {
      java.lang.Object ref = stocks_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stocks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tokenId_ = "";
      id_ = 0L;
      answer_ = QuizDefine.Answer.getDefaultInstance();
      stocks_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTokenId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAnswer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAnswer().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, answer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getStocksBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, answer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStocksBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static QuizAnswerRequest.QuizAnswer_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(QuizAnswerRequest.QuizAnswer_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quiz.QuizAnswer_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements QuizAnswerRequest.QuizAnswer_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QuizAnswerRequest.internal_static_quiz_QuizAnswer_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QuizAnswerRequest.internal_static_quiz_QuizAnswer_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QuizAnswerRequest.QuizAnswer_Request.class, QuizAnswerRequest.QuizAnswer_Request.Builder.class);
      }

      // Construct using QuizAnswerRequest.QuizAnswer_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAnswerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tokenId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (answerBuilder_ == null) {
          answer_ = QuizDefine.Answer.getDefaultInstance();
        } else {
          answerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        stocks_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QuizAnswerRequest.internal_static_quiz_QuizAnswer_Request_descriptor;
      }

      public QuizAnswerRequest.QuizAnswer_Request getDefaultInstanceForType() {
        return QuizAnswerRequest.QuizAnswer_Request.getDefaultInstance();
      }

      public QuizAnswerRequest.QuizAnswer_Request build() {
        QuizAnswerRequest.QuizAnswer_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public QuizAnswerRequest.QuizAnswer_Request buildPartial() {
        QuizAnswerRequest.QuizAnswer_Request result = new QuizAnswerRequest.QuizAnswer_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tokenId_ = tokenId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (answerBuilder_ == null) {
          result.answer_ = answer_;
        } else {
          result.answer_ = answerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stocks_ = stocks_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QuizAnswerRequest.QuizAnswer_Request) {
          return mergeFrom((QuizAnswerRequest.QuizAnswer_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QuizAnswerRequest.QuizAnswer_Request other) {
        if (other == QuizAnswerRequest.QuizAnswer_Request.getDefaultInstance()) return this;
        if (other.hasTokenId()) {
          bitField0_ |= 0x00000001;
          tokenId_ = other.tokenId_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAnswer()) {
          mergeAnswer(other.getAnswer());
        }
        if (other.hasStocks()) {
          bitField0_ |= 0x00000008;
          stocks_ = other.stocks_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTokenId()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasAnswer()) {
          
          return false;
        }
        if (!getAnswer().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QuizAnswerRequest.QuizAnswer_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QuizAnswerRequest.QuizAnswer_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string token_id = 1;
      private java.lang.Object tokenId_ = "";
      /**
       * <code>required string token_id = 1;</code>
       */
      public boolean hasTokenId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public java.lang.String getTokenId() {
        java.lang.Object ref = tokenId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tokenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenIdBytes() {
        java.lang.Object ref = tokenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder setTokenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tokenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder clearTokenId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tokenId_ = getDefaultInstance().getTokenId();
        onChanged();
        return this;
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder setTokenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tokenId_ = value;
        onChanged();
        return this;
      }

      // required uint64 id = 2;
      private long id_ ;
      /**
       * <code>required uint64 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 2;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required .quiz.Answer answer = 3;
      private QuizDefine.Answer answer_ = QuizDefine.Answer.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Answer, QuizDefine.Answer.Builder, QuizDefine.AnswerOrBuilder> answerBuilder_;
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public boolean hasAnswer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public QuizDefine.Answer getAnswer() {
        if (answerBuilder_ == null) {
          return answer_;
        } else {
          return answerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public Builder setAnswer(QuizDefine.Answer value) {
        if (answerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          answer_ = value;
          onChanged();
        } else {
          answerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public Builder setAnswer(
          QuizDefine.Answer.Builder builderForValue) {
        if (answerBuilder_ == null) {
          answer_ = builderForValue.build();
          onChanged();
        } else {
          answerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public Builder mergeAnswer(QuizDefine.Answer value) {
        if (answerBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              answer_ != QuizDefine.Answer.getDefaultInstance()) {
            answer_ =
              QuizDefine.Answer.newBuilder(answer_).mergeFrom(value).buildPartial();
          } else {
            answer_ = value;
          }
          onChanged();
        } else {
          answerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public Builder clearAnswer() {
        if (answerBuilder_ == null) {
          answer_ = QuizDefine.Answer.getDefaultInstance();
          onChanged();
        } else {
          answerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public QuizDefine.Answer.Builder getAnswerBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAnswerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      public QuizDefine.AnswerOrBuilder getAnswerOrBuilder() {
        if (answerBuilder_ != null) {
          return answerBuilder_.getMessageOrBuilder();
        } else {
          return answer_;
        }
      }
      /**
       * <code>required .quiz.Answer answer = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Answer, QuizDefine.Answer.Builder, QuizDefine.AnswerOrBuilder> 
          getAnswerFieldBuilder() {
        if (answerBuilder_ == null) {
          answerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QuizDefine.Answer, QuizDefine.Answer.Builder, QuizDefine.AnswerOrBuilder>(
                  answer_,
                  getParentForChildren(),
                  isClean());
          answer_ = null;
        }
        return answerBuilder_;
      }

      // optional string stocks = 5 [default = ""];
      private java.lang.Object stocks_ = "";
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public boolean hasStocks() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public java.lang.String getStocks() {
        java.lang.Object ref = stocks_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          stocks_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStocksBytes() {
        java.lang.Object ref = stocks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stocks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public Builder setStocks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        stocks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public Builder clearStocks() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stocks_ = getDefaultInstance().getStocks();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stocks = 5 [default = ""];</code>
       *
       * <pre>
       * 关联的股票ID
       * </pre>
       */
      public Builder setStocksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        stocks_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:quiz.QuizAnswer_Request)
    }

    static {
      defaultInstance = new QuizAnswer_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:quiz.QuizAnswer_Request)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quiz_QuizAnswer_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quiz_QuizAnswer_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030QuizAnswer_Request.proto\022\004quiz\032\020QuizDe" +
      "fine.proto\"b\n\022QuizAnswer_Request\022\020\n\010toke" +
      "n_id\030\001 \002(\t\022\n\n\002id\030\002 \002(\004\022\034\n\006answer\030\003 \002(\0132\014" +
      ".quiz.Answer\022\020\n\006stocks\030\005 \001(\t:\000B\002\n\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quiz_QuizAnswer_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quiz_QuizAnswer_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quiz_QuizAnswer_Request_descriptor,
              new java.lang.String[] { "TokenId", "Id", "Answer", "Stocks", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QuizDefine.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
