package cn.emoney.acg.data.protocol.quiz;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TeacherDetail_Reply.proto

public final class TeacherDetailReply {
  private TeacherDetailReply() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeacherDetail_ReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .quiz.Result result = 1;
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    QuizDefine.Result getResult();
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    QuizDefine.ResultOrBuilder getResultOrBuilder();

    // required uint32 id = 2;
    /**
     * <code>required uint32 id = 2;</code>
     *
     * <pre>
     *解答老师userId
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 2;</code>
     *
     * <pre>
     *解答老师userId
     * </pre>
     */
    int getId();

    // required string nick = 4;
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    boolean hasNick();
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    java.lang.String getNick();
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    // optional string icon = 5 [default = ""];
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    boolean hasIcon();
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    java.lang.String getIcon();
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getIconBytes();

    // optional string type = 6 [default = ""];
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // optional string title = 7 [default = ""];
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string desc = 8 [default = ""];
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // optional string level = 9 [default = ""];
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    java.lang.String getLevel();
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    com.google.protobuf.ByteString
        getLevelBytes();
  }
  /**
   * Protobuf type {@code quiz.TeacherDetail_Reply}
   */
  public static final class TeacherDetail_Reply extends
      com.google.protobuf.GeneratedMessage
      implements TeacherDetail_ReplyOrBuilder {
    // Use TeacherDetail_Reply.newBuilder() to construct.
    private TeacherDetail_Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TeacherDetail_Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TeacherDetail_Reply defaultInstance;
    public static TeacherDetail_Reply getDefaultInstance() {
      return defaultInstance;
    }

    public TeacherDetail_Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TeacherDetail_Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              QuizDefine.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(QuizDefine.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              nick_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              icon_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              type_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              title_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              desc_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              level_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TeacherDetailReply.internal_static_quiz_TeacherDetail_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TeacherDetailReply.internal_static_quiz_TeacherDetail_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeacherDetailReply.TeacherDetail_Reply.class, TeacherDetailReply.TeacherDetail_Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<TeacherDetail_Reply> PARSER =
        new com.google.protobuf.AbstractParser<TeacherDetail_Reply>() {
      public TeacherDetail_Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TeacherDetail_Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TeacherDetail_Reply> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .quiz.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private QuizDefine.Result result_;
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public QuizDefine.Result getResult() {
      return result_;
    }
    /**
     * <code>required .quiz.Result result = 1;</code>
     */
    public QuizDefine.ResultOrBuilder getResultOrBuilder() {
      return result_;
    }

    // required uint32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required uint32 id = 2;</code>
     *
     * <pre>
     *解答老师userId
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 id = 2;</code>
     *
     * <pre>
     *解答老师userId
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string nick = 4;
    public static final int NICK_FIELD_NUMBER = 4;
    private java.lang.Object nick_;
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    public boolean hasNick() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nick_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nick = 4;</code>
     *
     * <pre>
     *解答老师名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string icon = 5 [default = ""];
    public static final int ICON_FIELD_NUMBER = 5;
    private java.lang.Object icon_;
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string icon = 5 [default = ""];</code>
     *
     * <pre>
     *解答老师头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string type = 6 [default = ""];
    public static final int TYPE_FIELD_NUMBER = 6;
    private java.lang.Object type_;
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string type = 6 [default = ""];</code>
     *
     * <pre>
     *老师类型, 跟老师有关的都加上
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string title = 7 [default = ""];
    public static final int TITLE_FIELD_NUMBER = 7;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 7 [default = ""];</code>
     *
     * <pre>
     *老师头衔, 跟老师有关的都加上
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string desc = 8 [default = ""];
    public static final int DESC_FIELD_NUMBER = 8;
    private java.lang.Object desc_;
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 8 [default = ""];</code>
     *
     * <pre>
     *讲师描述（以后可扩展json）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string level = 9 [default = ""];
    public static final int LEVEL_FIELD_NUMBER = 9;
    private java.lang.Object level_;
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          level_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string level = 9 [default = ""];</code>
     *
     * <pre>
     *json 讲师评价;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      result_ = QuizDefine.Result.getDefaultInstance();
      id_ = 0;
      nick_ = "";
      icon_ = "";
      type_ = "";
      title_ = "";
      desc_ = "";
      level_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getNickBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getIconBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getDescBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getLevelBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNickBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIconBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDescBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLevelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherDetailReply.TeacherDetail_Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TeacherDetailReply.TeacherDetail_Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quiz.TeacherDetail_Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TeacherDetailReply.TeacherDetail_ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TeacherDetailReply.internal_static_quiz_TeacherDetail_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TeacherDetailReply.internal_static_quiz_TeacherDetail_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeacherDetailReply.TeacherDetail_Reply.class, TeacherDetailReply.TeacherDetail_Reply.Builder.class);
      }

      // Construct using TeacherDetailReply.TeacherDetail_Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = QuizDefine.Result.getDefaultInstance();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        nick_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        icon_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        level_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TeacherDetailReply.internal_static_quiz_TeacherDetail_Reply_descriptor;
      }

      public TeacherDetailReply.TeacherDetail_Reply getDefaultInstanceForType() {
        return TeacherDetailReply.TeacherDetail_Reply.getDefaultInstance();
      }

      public TeacherDetailReply.TeacherDetail_Reply build() {
        TeacherDetailReply.TeacherDetail_Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TeacherDetailReply.TeacherDetail_Reply buildPartial() {
        TeacherDetailReply.TeacherDetail_Reply result = new TeacherDetailReply.TeacherDetail_Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nick_ = nick_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icon_ = icon_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeacherDetailReply.TeacherDetail_Reply) {
          return mergeFrom((TeacherDetailReply.TeacherDetail_Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeacherDetailReply.TeacherDetail_Reply other) {
        if (other == TeacherDetailReply.TeacherDetail_Reply.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNick()) {
          bitField0_ |= 0x00000004;
          nick_ = other.nick_;
          onChanged();
        }
        if (other.hasIcon()) {
          bitField0_ |= 0x00000008;
          icon_ = other.icon_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000010;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000020;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000040;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasLevel()) {
          bitField0_ |= 0x00000080;
          level_ = other.level_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasNick()) {
          
          return false;
        }
        if (!getResult().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeacherDetailReply.TeacherDetail_Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeacherDetailReply.TeacherDetail_Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .quiz.Result result = 1;
      private QuizDefine.Result result_ = QuizDefine.Result.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder> resultBuilder_;
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.Result getResult() {
        if (resultBuilder_ == null) {
          return result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder setResult(QuizDefine.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder setResult(
          QuizDefine.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder mergeResult(QuizDefine.Result value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              result_ != QuizDefine.Result.getDefaultInstance()) {
            result_ =
              QuizDefine.Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = QuizDefine.Result.getDefaultInstance();
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.Result.Builder getResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      public QuizDefine.ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_;
        }
      }
      /**
       * <code>required .quiz.Result result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              QuizDefine.Result, QuizDefine.Result.Builder, QuizDefine.ResultOrBuilder>(
                  result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // required uint32 id = 2;
      private int id_ ;
      /**
       * <code>required uint32 id = 2;</code>
       *
       * <pre>
       *解答老师userId
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 id = 2;</code>
       *
       * <pre>
       *解答老师userId
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 2;</code>
       *
       * <pre>
       *解答老师userId
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 2;</code>
       *
       * <pre>
       *解答老师userId
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string nick = 4;
      private java.lang.Object nick_ = "";
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public boolean hasNick() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public Builder clearNick() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>required string nick = 4;</code>
       *
       * <pre>
       *解答老师名字
       * </pre>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nick_ = value;
        onChanged();
        return this;
      }

      // optional string icon = 5 [default = ""];
      private java.lang.Object icon_ = "";
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public java.lang.String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          icon_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIconBytes() {
        java.lang.Object ref = icon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public Builder setIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 5 [default = ""];</code>
       *
       * <pre>
       *解答老师头像
       * </pre>
       */
      public Builder setIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icon_ = value;
        onChanged();
        return this;
      }

      // optional string type = 6 [default = ""];
      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 6 [default = ""];</code>
       *
       * <pre>
       *老师类型, 跟老师有关的都加上
       * </pre>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }

      // optional string title = 7 [default = ""];
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 7 [default = ""];</code>
       *
       * <pre>
       *老师头衔, 跟老师有关的都加上
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        onChanged();
        return this;
      }

      // optional string desc = 8 [default = ""];
      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000040);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 8 [default = ""];</code>
       *
       * <pre>
       *讲师描述（以后可扩展json）
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        desc_ = value;
        onChanged();
        return this;
      }

      // optional string level = 9 [default = ""];
      private java.lang.Object level_ = "";
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public java.lang.String getLevel() {
        java.lang.Object ref = level_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          level_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLevelBytes() {
        java.lang.Object ref = level_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          level_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public Builder setLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000080);
        level_ = getDefaultInstance().getLevel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string level = 9 [default = ""];</code>
       *
       * <pre>
       *json 讲师评价;
       * </pre>
       */
      public Builder setLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        level_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:quiz.TeacherDetail_Reply)
    }

    static {
      defaultInstance = new TeacherDetail_Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:quiz.TeacherDetail_Reply)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quiz_TeacherDetail_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quiz_TeacherDetail_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TeacherDetail_Reply.proto\022\004quiz\032\020QuizD" +
      "efine.proto\"\237\001\n\023TeacherDetail_Reply\022\034\n\006r" +
      "esult\030\001 \002(\0132\014.quiz.Result\022\n\n\002id\030\002 \002(\r\022\014\n" +
      "\004nick\030\004 \002(\t\022\016\n\004icon\030\005 \001(\t:\000\022\016\n\004type\030\006 \001(" +
      "\t:\000\022\017\n\005title\030\007 \001(\t:\000\022\016\n\004desc\030\010 \001(\t:\000\022\017\n\005" +
      "level\030\t \001(\t:\000B\002\n\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quiz_TeacherDetail_Reply_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quiz_TeacherDetail_Reply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quiz_TeacherDetail_Reply_descriptor,
              new java.lang.String[] { "Result", "Id", "Nick", "Icon", "Type", "Title", "Desc", "Level", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QuizDefine.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
