package cn.emoney.acg.data.protocol.quiz;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TeacherStatus_Request.proto

public final class TeacherStatusRequest {
  private TeacherStatusRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeacherStatus_RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string token_id = 1;
    /**
     * <code>required string token_id = 1;</code>
     */
    boolean hasTokenId();
    /**
     * <code>required string token_id = 1;</code>
     */
    java.lang.String getTokenId();
    /**
     * <code>required string token_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenIdBytes();

    // optional uint64 tag = 2 [default = 0];
    /**
     * <code>optional uint64 tag = 2 [default = 0];</code>
     *
     * <pre>
     * 接受问题开关
     * </pre>
     */
    boolean hasTag();
    /**
     * <code>optional uint64 tag = 2 [default = 0];</code>
     *
     * <pre>
     * 接受问题开关
     * </pre>
     */
    long getTag();
  }
  /**
   * Protobuf type {@code quiz.TeacherStatus_Request}
   */
  public static final class TeacherStatus_Request extends
      com.google.protobuf.GeneratedMessage
      implements TeacherStatus_RequestOrBuilder {
    // Use TeacherStatus_Request.newBuilder() to construct.
    private TeacherStatus_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TeacherStatus_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TeacherStatus_Request defaultInstance;
    public static TeacherStatus_Request getDefaultInstance() {
      return defaultInstance;
    }

    public TeacherStatus_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TeacherStatus_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tokenId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tag_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TeacherStatusRequest.internal_static_quiz_TeacherStatus_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TeacherStatusRequest.internal_static_quiz_TeacherStatus_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeacherStatusRequest.TeacherStatus_Request.class, TeacherStatusRequest.TeacherStatus_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<TeacherStatus_Request> PARSER =
        new com.google.protobuf.AbstractParser<TeacherStatus_Request>() {
      public TeacherStatus_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TeacherStatus_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TeacherStatus_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string token_id = 1;
    public static final int TOKEN_ID_FIELD_NUMBER = 1;
    private java.lang.Object tokenId_;
    /**
     * <code>required string token_id = 1;</code>
     */
    public boolean hasTokenId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token_id = 1;</code>
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 tag = 2 [default = 0];
    public static final int TAG_FIELD_NUMBER = 2;
    private long tag_;
    /**
     * <code>optional uint64 tag = 2 [default = 0];</code>
     *
     * <pre>
     * 接受问题开关
     * </pre>
     */
    public boolean hasTag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 tag = 2 [default = 0];</code>
     *
     * <pre>
     * 接受问题开关
     * </pre>
     */
    public long getTag() {
      return tag_;
    }

    private void initFields() {
      tokenId_ = "";
      tag_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTokenId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, tag_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, tag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TeacherStatusRequest.TeacherStatus_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TeacherStatusRequest.TeacherStatus_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code quiz.TeacherStatus_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TeacherStatusRequest.TeacherStatus_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TeacherStatusRequest.internal_static_quiz_TeacherStatus_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TeacherStatusRequest.internal_static_quiz_TeacherStatus_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeacherStatusRequest.TeacherStatus_Request.class, TeacherStatusRequest.TeacherStatus_Request.Builder.class);
      }

      // Construct using TeacherStatusRequest.TeacherStatus_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tokenId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TeacherStatusRequest.internal_static_quiz_TeacherStatus_Request_descriptor;
      }

      public TeacherStatusRequest.TeacherStatus_Request getDefaultInstanceForType() {
        return TeacherStatusRequest.TeacherStatus_Request.getDefaultInstance();
      }

      public TeacherStatusRequest.TeacherStatus_Request build() {
        TeacherStatusRequest.TeacherStatus_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TeacherStatusRequest.TeacherStatus_Request buildPartial() {
        TeacherStatusRequest.TeacherStatus_Request result = new TeacherStatusRequest.TeacherStatus_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tokenId_ = tokenId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tag_ = tag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeacherStatusRequest.TeacherStatus_Request) {
          return mergeFrom((TeacherStatusRequest.TeacherStatus_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeacherStatusRequest.TeacherStatus_Request other) {
        if (other == TeacherStatusRequest.TeacherStatus_Request.getDefaultInstance()) return this;
        if (other.hasTokenId()) {
          bitField0_ |= 0x00000001;
          tokenId_ = other.tokenId_;
          onChanged();
        }
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTokenId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeacherStatusRequest.TeacherStatus_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeacherStatusRequest.TeacherStatus_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string token_id = 1;
      private java.lang.Object tokenId_ = "";
      /**
       * <code>required string token_id = 1;</code>
       */
      public boolean hasTokenId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public java.lang.String getTokenId() {
        java.lang.Object ref = tokenId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tokenId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenIdBytes() {
        java.lang.Object ref = tokenId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder setTokenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tokenId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder clearTokenId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tokenId_ = getDefaultInstance().getTokenId();
        onChanged();
        return this;
      }
      /**
       * <code>required string token_id = 1;</code>
       */
      public Builder setTokenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tokenId_ = value;
        onChanged();
        return this;
      }

      // optional uint64 tag = 2 [default = 0];
      private long tag_ ;
      /**
       * <code>optional uint64 tag = 2 [default = 0];</code>
       *
       * <pre>
       * 接受问题开关
       * </pre>
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 tag = 2 [default = 0];</code>
       *
       * <pre>
       * 接受问题开关
       * </pre>
       */
      public long getTag() {
        return tag_;
      }
      /**
       * <code>optional uint64 tag = 2 [default = 0];</code>
       *
       * <pre>
       * 接受问题开关
       * </pre>
       */
      public Builder setTag(long value) {
        bitField0_ |= 0x00000002;
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 tag = 2 [default = 0];</code>
       *
       * <pre>
       * 接受问题开关
       * </pre>
       */
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tag_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:quiz.TeacherStatus_Request)
    }

    static {
      defaultInstance = new TeacherStatus_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:quiz.TeacherStatus_Request)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_quiz_TeacherStatus_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_quiz_TeacherStatus_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033TeacherStatus_Request.proto\022\004quiz\"9\n\025T" +
      "eacherStatus_Request\022\020\n\010token_id\030\001 \002(\t\022\016" +
      "\n\003tag\030\002 \001(\004:\0010B\002\n\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_quiz_TeacherStatus_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_quiz_TeacherStatus_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_quiz_TeacherStatus_Request_descriptor,
              new java.lang.String[] { "TokenId", "Tag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
